Repository cncf/k8s-conformance, pull requests merged in 2020-08, with the labels that each got.

#1077 Update conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1078 Update conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1079 Update conformance results for IKS v1.16
  v1.16/iks/PRODUCT.yaml
  v1.16/iks/e2e.log
  v1.16/iks/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1080 Update conformance results for v1.17/ibm-openshift
  v1.17/ibm-openshift/PRODUCT.yaml
  v1.17/ibm-openshift/e2e.log
  v1.17/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1081 Update conformance results for v1.16/ibm-openshift
  v1.16/ibm-openshift/PRODUCT.yaml
  v1.16/ibm-openshift/e2e.log
  v1.16/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1065 Conformance results for China Mobile CMIT PaaS on kubernetes v1.18
  v1.18/chinamobile-cmit-paas/PRODUCT.yaml
  v1.18/chinamobile-cmit-paas/README.md
  v1.18/chinamobile-cmit-paas/e2e.log
  v1.18/chinamobile-cmit-paas/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1067 Conformance results for v1.17/ELASTX
  v1.17/elastx/PRODUCT.yaml
  v1.17/elastx/README.md
  v1.17/elastx/e2e.log
  v1.17/elastx/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1073 Conformance results for v1.18/lokomotive
  v1.18/lokomotive/PRODUCT.yaml
  v1.18/lokomotive/README.md
  v1.18/lokomotive/e2e.log
  v1.18/lokomotive/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1082 Conformance results for v1.18/KubeOperator
  v1.18/kubeoperator/PRODUCT.yaml
  v1.18/kubeoperator/README.md
  v1.18/kubeoperator/cluster.png
  v1.18/kubeoperator/e2e.log
  v1.18/kubeoperator/junit_01.xml
  v1.18/kubeoperator/sonobuoy.tar.gz
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1083 Conformance results for v1.19/kube-up-gce
  v1.19/kube-up-gce/PRODUCT.yaml
  v1.19/kube-up-gce/README.md
  v1.19/kube-up-gce/e2e.log
  v1.19/kube-up-gce/junit_01.xml
Labels: release-documents-checked, release-v1.19

#1085 Conformance results for v1.19/typhoon
  v1.19/typhoon/PRODUCT.yaml
  v1.19/typhoon/README.md
  v1.19/typhoon/e2e.log
  v1.19/typhoon/junit_01.xml
Labels: release-documents-checked, release-v1.19

#1086 Conformance results for v1.19/scaleway
  v1.19/scaleway/PRODUCT.yaml
  v1.19/scaleway/README.md
  v1.19/scaleway/e2e.log
  v1.19/scaleway/junit_01.xml
Labels: release-documents-checked, release-v1.19

#1088 Conformance results for v1.19/kubeone
  v1.19/kubeone/PRODUCT.yaml
  v1.19/kubeone/README.md
  v1.19/kubeone/e2e.log
  v1.19/kubeone/junit_01.xml
Labels: release-documents-checked, release-v1.19

#1071 Conformance results of NIFCLOUD Hatoba v1.16
  v1.16/nifcloud-hatoba/PRODUCT.yaml
  v1.16/nifcloud-hatoba/README.md
  v1.16/nifcloud-hatoba/e2e.log
  v1.16/nifcloud-hatoba/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16
