Repository cncf/k8s-conformance, pull requests merged in 2020-09, with the labels that each got.

#1089 Rename Loodse to Kubermatic
  v1.10/kubermatic/PRODUCT.yaml
  v1.11/kubermatic/PRODUCT.yaml
  v1.12/kubermatic/PRODUCT.yaml
  v1.13/kubermatic/PRODUCT.yaml
  v1.14/kubeone/PRODUCT.yaml
  v1.14/kubermatic/PRODUCT.yaml
  v1.15/kubeone/PRODUCT.yaml
  v1.15/kubermatic/PRODUCT.yaml
  v1.16/kubeone/PRODUCT.yaml
  v1.16/kubermatic/PRODUCT.yaml
  v1.17/kubeone/PRODUCT.yaml
  v1.18/kubeone/PRODUCT.yaml
  v1.7/kubermatic/PRODUCT.yaml
  v1.8/kubermatic/PRODUCT.yaml
  v1.9/kubermatic/PRODUCT.yaml
Labels: not-verifiable

#1090 Conformance results for v1.18/banzaicloud-pke
  v1.18/banzaicloud-pke/PRODUCT.yaml
  v1.18/banzaicloud-pke/README.md
  v1.18/banzaicloud-pke/e2e.log
  v1.18/banzaicloud-pke/junit_01.xml
  v1.18/banzaicloud-pke/sonobuoy.tar.gz
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1091 Conformance results for v1.18/flexkube
  v1.18/flexkube/PRODUCT.yaml
  v1.18/flexkube/README.md
  v1.18/flexkube/e2e.log
  v1.18/flexkube/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1092 Conformance results for v1.17/kubermatic
  v1.17/kubermatic/PRODUCT.yaml
  v1.17/kubermatic/README.md
  v1.17/kubermatic/e2e.log
  v1.17/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1093 Conformance results for v1.18/kubermatic
  v1.18/kubermatic/PRODUCT.yaml
  v1.18/kubermatic/README.md
  v1.18/kubermatic/e2e.log
  v1.18/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1096 Conformance results for v1.18/TencentCloud
  v1.18/tencentcloud/CreateTkeCluster.png
  v1.18/tencentcloud/PRODUCT.yaml
  v1.18/tencentcloud/README.md
  v1.18/tencentcloud/e2e.log
  v1.18/tencentcloud/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1098 Conformance results for v1.17/MetalK8s
  v1.17/MetalK8s/PRODUCT.yaml
  v1.17/MetalK8s/README.md
  v1.17/MetalK8s/e2e.log
  v1.17/MetalK8s/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1100 Conformance results for v1.19/kubermatic
  v1.19/kubermatic/PRODUCT.yaml
  v1.19/kubermatic/README.md
  v1.19/kubermatic/e2e.log
  v1.19/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1101 Conformance results for v1.17/ntnx-karbon
  v1.17/ntnx-karbon/PRODUCT.yaml
  v1.17/ntnx-karbon/README.md
  v1.17/ntnx-karbon/e2e.log
  v1.17/ntnx-karbon/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1103 Conformance results for v1.18/AgileStacks
  v1.18/agilestacks/PRODUCT.yaml
  v1.18/agilestacks/README.md
  v1.18/agilestacks/e2e.log
  v1.18/agilestacks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1104 Conformance results for v1.17/oke
  v1.17/oke/PRODUCT.yaml
  v1.17/oke/README.md
  v1.17/oke/e2e.log
  v1.17/oke/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1105 Conformance results for v1.18/ntnx-karbon
  v1.18/ntnx-karbon/PRODUCT.yaml
  v1.18/ntnx-karbon/README.md
  v1.18/ntnx-karbon/e2e.log
  v1.18/ntnx-karbon/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1076 Conformance results for v1.16/roost
  v1.16/roost/PRODUCT.yaml
  v1.16/roost/README.md
  v1.16/roost/e2e.log
  v1.16/roost/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1074 Conformance results for v1.17/roost
  v1.17/roost/PRODUCT.yaml
  v1.17/roost/README.md
  v1.17/roost/e2e.log
  v1.17/roost/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1075 Conformance results for v1.18/roost
  v1.18/roost/PRODUCT.yaml
  v1.18/roost/README.md
  v1.18/roost/e2e.log
  v1.18/roost/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1106 Conformance results for v1.18/Diamanti-Spektra
  v1.18/Diamanti-Spektra/Product.yaml
  v1.18/Diamanti-Spektra/README.md
  v1.18/Diamanti-Spektra/e2e.log
  v1.18/Diamanti-Spektra/junit_01.xml
Labels: not-verifiable

#1108 Conformance results for v1.18/Teamsun
  v1.18/Teamsun/PRODUCT.yaml
  v1.18/Teamsun/README.md
  v1.18/Teamsun/e2e.log
  v1.18/Teamsun/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1084 Conformance Results for v1.18/AlibabaCloud
  v1.18/alicloud/PRODUCT.yaml
  v1.18/alicloud/README.md
  v1.18/alicloud/cluster.png
  v1.18/alicloud/e2e.log
  v1.18/alicloud/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1110 Add conformance test results for k8s v1.18/RKE
  v1.18/rke/PRODUCT.yaml
  v1.18/rke/README.md
  v1.18/rke/e2e.log
  v1.18/rke/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1119 Conformance results for v1.18/starlingx
  v1.18/starlingx/PRODUCT.yaml
  v1.18/starlingx/README.md
  v1.18/starlingx/e2e.log
  v1.18/starlingx/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1122 Conformance results for v1.17/Chinaunicom-kubernetes-engine
  v1.17/chinaunicom-kubernetes-engine/PRODUCT.yaml
  v1.17/chinaunicom-kubernetes-engine/README.md
  v1.17/chinaunicom-kubernetes-engine/e2e.log
  v1.17/chinaunicom-kubernetes-engine/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1123 Conformance results for v1.18/snaps-kubernetes
  v1.18/snaps-kubernetes/PRODUCT.yaml
  v1.18/snaps-kubernetes/README.md
  v1.18/snaps-kubernetes/e2e.log
  v1.18/snaps-kubernetes/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1124 Change product name from "HPE Container Platform" to "HPE Ezmeral Container Platform" for k8s versions 1.16, 1.17, 1.18
  v1.16/hpe/PRODUCT.yaml
  v1.16/hpe/README.md
  v1.17/hpe/PRODUCT.yaml
  v1.17/hpe/README.md
  v1.18/hpe/PRODUCT.yaml
  v1.18/hpe/README.md
Labels: not-verifiable

#1095 Conformance results for v1.18/mirantis-docker-enterprise
  v1.18/mirantis-docker-enterprise/PRODUCT.yaml
  v1.18/mirantis-docker-enterprise/README.md
  v1.18/mirantis-docker-enterprise/e2e.log
  v1.18/mirantis-docker-enterprise/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1125 Conformance results for v1.19/talos
  v1.19/talos/PRODUCT.yaml
  v1.19/talos/README.md
  v1.19/talos/e2e.log
  v1.19/talos/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1109 Conformance results for v1.19/asuscloudinfra
  v1.19/asuscloudinfra/PRODUCT.yaml
  v1.19/asuscloudinfra/README.md
  v1.19/asuscloudinfra/e2e.log
  v1.19/asuscloudinfra/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1111 Add conformance test results for k8s v1.17/Rancher
  v1.17/rancher/PRODUCT.yaml
  v1.17/rancher/README.md
  v1.17/rancher/e2e.log
  v1.17/rancher/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1112 Add conformance test results for k8s v1.18/Rancher
  v1.18/rancher/PRODUCT.yaml
  v1.18/rancher/README.md
  v1.18/rancher/e2e.log
  v1.18/rancher/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1126 Conformance results for v1.19/easystack
  v1.19/easystack/PRODUCT.yaml
  v1.19/easystack/README.md
  v1.19/easystack/e2e.log
  v1.19/easystack/images/k8s1.png
  v1.19/easystack/images/k8s2.png
  v1.19/easystack/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1130 Conformance results for v1.17/NIFCLOUD Hatoba
  v1.17/nifcloud-hatoba/PRODUCT.yaml
  v1.17/nifcloud-hatoba/README.md
  v1.17/nifcloud-hatoba/e2e.log
  v1.17/nifcloud-hatoba/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1131 Conformance results for v1.18/NIFCLOUD Hatoba
  v1.18/nifcloud-hatoba/PRODUCT.yaml
  v1.18/nifcloud-hatoba/README.md
  v1.18/nifcloud-hatoba/e2e.log
  v1.18/nifcloud-hatoba/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1132 add conformance for QKE3.0.0/v1.17
  v1.17/QKE/PRODUCT.yaml
  v1.17/QKE/QingCloudLogo.ai
  v1.17/QKE/README.md
  v1.17/QKE/e2e.log
  v1.17/QKE/guide1.png
  v1.17/QKE/guide2.png
  v1.17/QKE/guide3.png
  v1.17/QKE/guide4.png
  v1.17/QKE/guide5.png
  v1.17/QKE/guide6.png
  v1.17/QKE/guide7.png
  v1.17/QKE/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1133 Conformance results for v1.18/openshift-dedicated
  v1.18/openshift-dedicated/PRODUCT.yaml
  v1.18/openshift-dedicated/README.md
  v1.18/openshift-dedicated/e2e.log
  v1.18/openshift-dedicated/junit_01.xml
Labels: release-documents-checked, release-v1.18, required-tests-missing

#1128 Conformance results for v1.17/elastisys-compliant-kubernetes
  v1.17/elastisys-compliant-kubernetes/PRODUCT.yaml
  v1.17/elastisys-compliant-kubernetes/README.md
  v1.17/elastisys-compliant-kubernetes/e2e.log
  v1.17/elastisys-compliant-kubernetes/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1114 Conformance Results for v1.18/Jdcloud
  v1.18/jdcloud/PRODUCT.yaml
  v1.18/jdcloud/README.md
  v1.18/jdcloud/e2e.log
  v1.18/jdcloud/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1121 Conformance results for v1.19/Moondog
  v1.19/moondog/PRODUCT.yaml
  v1.19/moondog/README.md
  v1.19/moondog/e2e.log
  v1.19/moondog/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1134 Confromance results for v1.18/robin.io
  v1.18/robin.io/PRODUCT.yaml
  v1.18/robin.io/README.md
  v1.18/robin.io/e2e.log
  v1.18/robin.io/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1116 Conformance Results for v1.19/JDOS
  v1.19/JDOS/PRODUCT.yaml
  v1.19/JDOS/README.md
  v1.19/JDOS/e2e.log
  v1.19/JDOS/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1135 Conformance test results for v1.19/k3s
  v1.19/k3s/PRODUCT.yaml
  v1.19/k3s/README.md
  v1.19/k3s/e2e.log
  v1.19/k3s/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1136 Update conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1137 Update conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1138 Update conformance results for IKS v1.16
  v1.16/iks/PRODUCT.yaml
  v1.16/iks/e2e.log
  v1.16/iks/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1139 Update conformance results for v1.17/ibm-openshift
  v1.17/ibm-openshift/PRODUCT.yaml
  v1.17/ibm-openshift/e2e.log
  v1.17/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1140 Update conformance results for v1.16/ibm-openshift
  v1.16/ibm-openshift/PRODUCT.yaml
  v1.16/ibm-openshift/e2e.log
  v1.16/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1127 Conformance results for v1.18/Chinaunicom-kubernetes-engine
  v1.18/chinaunicom-kubernetes-engine/PRODUCT.yaml
  v1.18/chinaunicom-kubernetes-engine/README.md
  v1.18/chinaunicom-kubernetes-engine/e2e.log
  v1.18/chinaunicom-kubernetes-engine/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1141 Conformance results for v1.19/mesosphere-kubernetes-engine
  v1.19/mesosphere-kubernetes-engine/PRODUCT.yaml
  v1.19/mesosphere-kubernetes-engine/README.md
  v1.19/mesosphere-kubernetes-engine/e2e.log
  v1.19/mesosphere-kubernetes-engine/junit_01.xml
  v1.19/mesosphere-kubernetes-engine/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19
