Repository cncf/k8s-conformance, pull requests merged in 2020-11, with the labels that each got.

#1147 add Conformance results for v1.18/InsureMO
  v1.18/insuremo/PRODUCT.yaml
  v1.18/insuremo/README.md
  v1.18/insuremo/e2e.log
  v1.18/insuremo/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1188 Conformance results for v1.19/openshift
  v1.19/openshift/PRODUCT.yaml
  v1.19/openshift/README.md
  v1.19/openshift/e2e.log
  v1.19/openshift/junit_01.xml
Labels: not-verifiable

#1189 Conformance results for v1.19/rke
  v1.19/rke/PRODUCT.yaml
  v1.19/rke/README.md
  v1.19/rke/e2e.log
  v1.19/rke/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1191 Add conformance test results for k8s v1.19/Rancher
  v1.19/rancher/PRODUCT.yaml
  v1.19/rancher/README.md
  v1.19/rancher/e2e.log
  v1.19/rancher/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1187 Conformance results for v1.17/innovo-imke
  v1.17/innovo-imke/PRODUCT.yaml
  v1.17/innovo-imke/README.md
  v1.17/innovo-imke/e2e.log
  v1.17/innovo-imke/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1196 Add conformance results for v1.19/ovh
  v1.19/ovh/PRODUCT.yaml
  v1.19/ovh/README.md
  v1.19/ovh/e2e.log
  v1.19/ovh/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1199 Conformance test results for v1.19/ericsson-ccd
  v1.19/ericsson-ccd/README.md
  v1.19/ericsson-ccd/e2e.log
  v1.19/ericsson-ccd/junit_01.xml
  v1.19/ericsson-ccd/product.yaml
Labels: not-verifiable

#1202 Conformance results for v1.19/SamsungSDS-Kubernetes-Service
  v1.19/SamsungSDS-Kubernetes-Service/PRODUCT.yaml
  v1.19/SamsungSDS-Kubernetes-Service/README.md
  v1.19/SamsungSDS-Kubernetes-Service/e2e.log
  v1.19/SamsungSDS-Kubernetes-Service/junit_01.xml
Labels: not-verifiable

#1204 Conformance results for v1.18/weave-kubernetes-platform
  v1.18/weave-kubernetes-platform/PRODUCT.yaml
  v1.18/weave-kubernetes-platform/README.md
  v1.18/weave-kubernetes-platform/e2e.log
  v1.18/weave-kubernetes-platform/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1205 Conformance results for v1.19/weave-kubernetes-platform
  v1.19/weave-kubernetes-platform/PRODUCT.yaml
  v1.19/weave-kubernetes-platform/README.md
  v1.19/weave-kubernetes-platform/e2e.log
  v1.19/weave-kubernetes-platform/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1192 Conformance results for v1.17/cloudboostr
  v1.17/cloudboostr/PRODUCT.yaml
  v1.17/cloudboostr/README.md
  v1.17/cloudboostr/e2e.log
  v1.17/cloudboostr/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1190 change company name for compass
  v1.17/compass/PRODUCT.yaml
Labels: not-verifiable

#1207 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1208 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1209 Updated conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1212 Update conformance results for v1.16/ibm-openshift
  v1.16/ibm-openshift/PRODUCT.yaml
  v1.16/ibm-openshift/e2e.log
  v1.16/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1210 Update conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1211 Update conformance results for v1.17/ibm-openshift
  v1.17/ibm-openshift/PRODUCT.yaml
  v1.17/ibm-openshift/e2e.log
  v1.17/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1201 Conformance results for v1.18.10/mirantis-docker-enterprise
  v1.18/mirantis-docker-enterprise/PRODUCT.yaml
  v1.18/mirantis-docker-enterprise/README.md
  v1.18/mirantis-docker-enterprise/e2e.log
  v1.18/mirantis-docker-enterprise/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1206 Conformance results for v1.18/oke
  v1.18/oke/PRODUCT.yaml
  v1.18/oke/README.md
  v1.18/oke/e2e.log
  v1.18/oke/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1213 Conformance results for v1.19.4/cdk
  v1.19/cdk/PRODUCT.yaml
  v1.19/cdk/README.md
  v1.19/cdk/e2e.log
  v1.19/cdk/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1214 Conformance results for v1.19/kublr
  v1.19/kublr/PRODUCT.yaml
  v1.19/kublr/README.md
  v1.19/kublr/e2e.log
  v1.19/kublr/junit_01.xml
  v1.19/kublr/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1198 rename iNNOVO to GEC
  v1.14/gec-imke/PRODUCT.yaml
  v1.14/gec-imke/README.md
  v1.14/gec-imke/e2e.log
  v1.14/gec-imke/junit_01.xml
  v1.14/innovo-imke/PRODUCT.yaml
  v1.15/gec-imke/PRODUCT.yaml
  v1.15/gec-imke/README.md
  v1.15/gec-imke/e2e.log
  v1.15/gec-imke/junit_01.xml
  v1.15/innovo-imke/PRODUCT.yaml
  v1.16/gec-imke/PRODUCT.yaml
  v1.16/gec-imke/README.md
  v1.16/gec-imke/e2e.log
  v1.16/gec-imke/junit_01.xml
  v1.16/innovo-imke/PRODUCT.yaml
  v1.17/gec-imke/PRODUCT.yaml
  v1.17/gec-imke/README.md
  v1.17/gec-imke/e2e.log
  v1.17/gec-imke/junit_01.xml
  v1.17/innovo-imke/PRODUCT.yaml
Labels: not-verifiable

#1203 Conformance results for v1.19/k0s
  v1.19/k0s/PRODUCT.yaml
  v1.19/k0s/README.md
  v1.19/k0s/e2e.log
  v1.19/k0s/junit_01.xml
  v1.19/k0s/sonobuoy_results.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1197 Conformance results for v1.18/opennebula-kubernetes-appliance
  v1.18/opennebula-kubernetes-appliance/PRODUCT.yaml
  v1.18/opennebula-kubernetes-appliance/README.md
  v1.18/opennebula-kubernetes-appliance/e2e.log
  v1.18/opennebula-kubernetes-appliance/junit_01.xml
  v1.18/opennebula-kubernetes-appliance/sonobuoy.tar.gz
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18
