Repository cncf/k8s-conformance, pull requests merged in 2020-12, with the labels that each got.

#1216 Conformance results for v1.18/giantswarm-aws
  v1.18/giantswarm-aws/PRODUCT.yaml
  v1.18/giantswarm-aws/README.md
  v1.18/giantswarm-aws/e2e.log
  v1.18/giantswarm-aws/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1217 Conformance results for v1.19/kubic
  v1.19/kubic/PRODUCT.yaml
  v1.19/kubic/README.md
  v1.19/kubic/e2e.log
  v1.19/kubic/junit_01.xml
  v1.19/kubic/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1218 Conformance results for v1.18/olcne
  v1.18/olcne/PRODUCT.yaml
  v1.18/olcne/README.md
  v1.18/olcne/e2e.log
  v1.18/olcne/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1219 Conformance results for v1.18/Breeze
  v1.18/Breeze/PRODUCT.yaml
  v1.18/Breeze/README.md
  v1.18/Breeze/e2e.log
  v1.18/Breeze/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1221 Conformance results for v1.18/ccp
  v1.18/ccp/PRODUCT.yaml
  v1.18/ccp/README.md
  v1.18/ccp/e2e.log
  v1.18/ccp/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1224 kbsys_Bizmicro conformance kubernetes v1.19
  v1.19/kbsys_Bizmicro_Portal_New/PRODUCT.yaml
  v1.19/kbsys_Bizmicro_Portal_New/README.md
  v1.19/kbsys_Bizmicro_Portal_New/e2e.log
  v1.19/kbsys_Bizmicro_Portal_New/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1225 Conformance results for v1.19/k0s v0.8.0
  v1.19/k0s/PRODUCT.yaml
  v1.19/k0s/README.md
  v1.19/k0s/e2e.log
  v1.19/k0s/junit_01.xml
  v1.19/k0s/sonobuoy_results.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1229 Add K8splus v1.19 conformance
  v1.19/k8splus/PRODUCT.yaml
  v1.19/k8splus/README.md
  v1.19/k8splus/e2e.log
  v1.19/k8splus/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1231 Conformance results for v1.19/netease-qingzhou
  v1.19/netease-qingzhou/PRODUCT.yaml
  v1.19/netease-qingzhou/README.md
  v1.19/netease-qingzhou/e2e.log
  v1.19/netease-qingzhou/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1226 EKS-D v1.18 conformance
  v1.18/eks-d/PRODUCT.yaml
  v1.18/eks-d/README.md
  v1.18/eks-d/e2e.log
  v1.18/eks-d/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1227 Conformance results for v1.18/kubespray
  v1.18/kubespray/PRODUCT.yaml
  v1.18/kubespray/README.md
  v1.18/kubespray/e2e.log
  v1.18/kubespray/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1232 Conformance results for v1.18/MetalK8s
  v1.18/MetalK8s/PRODUCT.yaml
  v1.18/MetalK8s/README.md
  v1.18/MetalK8s/e2e.log
  v1.18/MetalK8s/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1234 Conformance results for v1.18/giantswarm-azure
  v1.18/giantswarm-azure/PRODUCT.yaml
  v1.18/giantswarm-azure/README.md
  v1.18/giantswarm-azure/e2e.log
  v1.18/giantswarm-azure/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1235 Conformance results for v1.18/giantswarm-kvm
  v1.18/giantswarm-kvm/PRODUCT.yaml
  v1.18/giantswarm-kvm/README.md
  v1.18/giantswarm-kvm/e2e.log
  v1.18/giantswarm-kvm/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1236 Conformance results for v1.18/aks-engine-azurestack
  v1.18/aks-engine-azurestack/PRODUCT.yaml
  v1.18/aks-engine-azurestack/README.md
  v1.18/aks-engine-azurestack/e2e.log
  v1.18/aks-engine-azurestack/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1239 Conformance results for v1.18/baiducloud
  v1.18/baiducloud/PRODUCT.yaml
  v1.18/baiducloud/README.md
  v1.18/baiducloud/e2e.log
  v1.18/baiducloud/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1241 Conformance results for v1.19/HUAWEICLOUD Cloud Container Engine
  v1.19/huawei-cce/PRODUCT.yaml
  v1.19/huawei-cce/README.md
  v1.19/huawei-cce/e2e.log
  v1.19/huawei-cce/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1243 Conformance results for v1.18/gec-imke
  v1.18/gec-imke/PRODUCT.yaml
  v1.18/gec-imke/README.md
  v1.18/gec-imke/e2e.log
  v1.18/gec-imke/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1244 Conformance results for v1.18/platform9
  v1.18/platform9/PRODUCT.yaml
  v1.18/platform9/README.md
  v1.18/platform9/e2e.log
  v1.18/platform9/junit_01.xml
  v1.18/platform9/sonobuoy.tar.gz
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1242 Conformance results for v1.18/UCloud
  v1.18/UCloud/PRODUCT.yaml
  v1.18/UCloud/e2e.log
  v1.18/UCloud/junit_01.xml
  v1.18/UCloud/readme.md
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1220 Add conformance results for v1.19/minikube
  v1.19/minikube/PRODUCT.yaml
  v1.19/minikube/README.md
  v1.19/minikube/e2e.log
  v1.19/minikube/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1230 Conformance results for v1.19/h3c-cloudos
  v1.19/h3c-cloudos/PRODUCT.yaml
  v1.19/h3c-cloudos/README.md
  v1.19/h3c-cloudos/e2e.log
  v1.19/h3c-cloudos/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1237 Conformance results for v1.20/scaleway
  v1.20/scaleway/PRODUCT.yaml
  v1.20/scaleway/README.md
  v1.20/scaleway/e2e.log
  v1.20/scaleway/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1238 Conformance results for v1.20/typhoon
  v1.20/typhoon/PRODUCT.yaml
  v1.20/typhoon/README.md
  v1.20/typhoon/e2e.log
  v1.20/typhoon/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1245 Conformance results for v1.20/k8s-tew
  v1.20/k8s-tew/PRODUCT.yaml
  v1.20/k8s-tew/README.md
  v1.20/k8s-tew/e2e.log
  v1.20/k8s-tew/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1246 Conformance results for v1.18/ventus
  v1.18/ventus/PRODUCT.yaml
  v1.18/ventus/README.md
  v1.18/ventus/e2e.log
  v1.18/ventus/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1247 Conformance results for v1.19/ncs
  v1.19/ncs/202012110737_sonobuoy_8cba0bea-8e44-4b33-bb3f-f05f2c07758f.tar.gz
  v1.19/ncs/PRODUCT.yaml
  v1.19/ncs/README.md
  v1.19/ncs/e2e.log
  v1.19/ncs/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1250 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1251 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1252 Updated conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1253 Conformance results for v1.20/caih
  v1.20/caih/PRODUCT.yaml
  v1.20/caih/README.md
  v1.20/caih/e2e.log
  v1.20/caih/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1254 Conformance results for v1.20/symplegma
  v1.20/symplegma/PRODUCT.yaml
  v1.20/symplegma/README.md
  v1.20/symplegma/e2e.log
  v1.20/symplegma/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1256 Add Conformance results for v1.19/clearlinux
  v1.19/clearlinux/PRODUCT.yaml
  v1.19/clearlinux/README.md
  v1.19/clearlinux/e2e.log
  v1.19/clearlinux/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1259 Conformance results for v1.19/Breeze
  v1.19/Breeze/PRODUCT.yaml
  v1.19/Breeze/README.md
  v1.19/Breeze/e2e.log
  v1.19/Breeze/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1260 Conformance results for v1.20/Breeze
  v1.20/Breeze/PRODUCT.yaml
  v1.20/Breeze/README.md
  v1.20/Breeze/e2e.log
  v1.20/Breeze/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1233 Conformance results for v1.19/Vanillastack
  v1.19/vanillastack/Certified_Kubernetes_Form.pdf
  v1.19/vanillastack/PRODUCT.yaml
  v1.19/vanillastack/README.md
  v1.19/vanillastack/e2e.log
  v1.19/vanillastack/junit_01.xml
  v1.19/vanillastack/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1258 Conformance results for v1.19/WiseCloud
  v1.19/WiseCloud/PRODUCT.yaml
  v1.19/WiseCloud/README.md
  v1.19/WiseCloud/e2e.log
  v1.19/WiseCloud/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1240 Conformance results for v1.18/airship
  v1.18/airship/PRODUCT.yaml
  v1.18/airship/README.md
  v1.18/airship/e2e.log
  v1.18/airship/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1261 Conformance results for v1.18/wksctl
  v1.18/wksctl/PRODUCT.yaml
  v1.18/wksctl/README.md
  v1.18/wksctl/e2e.log
  v1.18/wksctl/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1262 Conformance results for v1.19/wksctl
  v1.19/wksctl/PRODUCT.yaml
  v1.19/wksctl/README.md
  v1.19/wksctl/e2e.log
  v1.19/wksctl/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1265 Conformance results for v1.19/openpalette 🐳
  v1.19/openpalette/PRODUCT.yaml
  v1.19/openpalette/README.md
  v1.19/openpalette/e2e.log
  v1.19/openpalette/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1266 Conformance results for v1.18/triton-kubernetes
  v1.18/triton-kubernetes/PRODUCT.yaml
  v1.18/triton-kubernetes/README.md
  v1.18/triton-kubernetes/e2e.log
  v1.18/triton-kubernetes/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1267 Conformance results for v1.20/k0s v0.9.0
  v1.20/k0s/PRODUCT.yaml
  v1.20/k0s/README.md
  v1.20/k0s/e2e.log
  v1.20/k0s/junit_01.xml
  v1.20/k0s/sonobuoy_results.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1269 Conformance test results for v1.20/k3s
  v1.20/k3s/PRODUCT.yaml
  v1.20/k3s/README.md
  v1.20/k3s/e2e.log
  v1.20/k3s/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1268 Conformance results for v1.20/BoCloud
  v1.20/bocloud/PRODUCT.yaml
  v1.20/bocloud/README.md
  v1.20/bocloud/e2e.log
  v1.20/bocloud/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1271 Conformance results for v1.18/mcs
  v1.18/mcs/PRODUCT.yaml
  v1.18/mcs/README.md
  v1.18/mcs/e2e.log
  v1.18/mcs/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1272 Conformance results for v1.19/mcs
  v1.19/mcs/PRODUCT.yaml
  v1.19/mcs/README.md
  v1.19/mcs/e2e.log
  v1.19/mcs/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1273 Conformance results for v1.19/compass
  v1.19/compass/PRODUCT.yaml
  v1.19/compass/README.md
  v1.19/compass/e2e.log
  v1.19/compass/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19
