Repository cncf/k8s-conformance, pull requests merged in 2020-10, with the labels that each got.

#1145 Conformance results for v1.18/ELASTX
  v1.18/elastx/PRODUCT.yaml
  v1.18/elastx/README.md
  v1.18/elastx/e2e.log
  v1.18/elastx/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1146 Conformance results for v1.19/Chinaunicom-kubernetes-engine
  v1.19/chinaunicom-kubernetes-engine/PRODUCT.yaml
  v1.19/chinaunicom-kubernetes-engine/README.md
  v1.19/chinaunicom-kubernetes-engine/e2e.log
  v1.19/chinaunicom-kubernetes-engine/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1148 Conformance Results for v1.19/Gardener
  v1.19/gardener-alicloud/PRODUCT.yaml
  v1.19/gardener-alicloud/README.md
  v1.19/gardener-alicloud/e2e.log
  v1.19/gardener-alicloud/junit_01.xml
  v1.19/gardener-aws/PRODUCT.yaml
  v1.19/gardener-aws/README.md
  v1.19/gardener-aws/e2e.log
  v1.19/gardener-aws/junit_01.xml
  v1.19/gardener-azure/PRODUCT.yaml
  v1.19/gardener-azure/README.md
  v1.19/gardener-azure/e2e.log
  v1.19/gardener-azure/junit_01.xml
  v1.19/gardener-gcp/PRODUCT.yaml
  v1.19/gardener-gcp/README.md
  v1.19/gardener-gcp/e2e.log
  v1.19/gardener-gcp/junit_01.xml
  v1.19/gardener-openstack/PRODUCT.yaml
  v1.19/gardener-openstack/README.md
  v1.19/gardener-openstack/e2e.log
  v1.19/gardener-openstack/junit_01.xml
  v1.19/sap-cp-alicloud/PRODUCT.yaml
  v1.19/sap-cp-alicloud/README.md
  v1.19/sap-cp-alicloud/e2e.log
  v1.19/sap-cp-alicloud/junit_01.xml
  v1.19/sap-cp-aws/PRODUCT.yaml
  v1.19/sap-cp-aws/README.md
  v1.19/sap-cp-aws/e2e.log
  v1.19/sap-cp-aws/junit_01.xml
  v1.19/sap-cp-azure/PRODUCT.yaml
  v1.19/sap-cp-azure/README.md
  v1.19/sap-cp-azure/e2e.log
  v1.19/sap-cp-azure/junit_01.xml
  v1.19/sap-cp-gcp/PRODUCT.yaml
  v1.19/sap-cp-gcp/README.md
  v1.19/sap-cp-gcp/e2e.log
  v1.19/sap-cp-gcp/junit_01.xml
  v1.19/sap-cp-openstack/PRODUCT.yaml
  v1.19/sap-cp-openstack/README.md
  v1.19/sap-cp-openstack/e2e.log
  v1.19/sap-cp-openstack/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1149 Update v1.18/docker-desktop-for-{mac,win} for 2.4.0.0 stable
  v1.18/docker-desktop-for-mac/PRODUCT.yaml
  v1.18/docker-desktop-for-mac/README.md
  v1.18/docker-desktop-for-mac/e2e.log
  v1.18/docker-desktop-for-mac/junit_01.xml
  v1.18/docker-desktop-for-win/PRODUCT.yaml
  v1.18/docker-desktop-for-win/README.md
  v1.18/docker-desktop-for-win/e2e.log
  v1.18/docker-desktop-for-win/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1150 TKGI / PKS 1.9 conformance with Kubernetes v1.18
  v1.18/pks/PRODUCT.yaml
  v1.18/pks/README.md
  v1.18/pks/e2e.log
  v1.18/pks/junit_01.xml
Labels: not-verifiable

#1153 Conformance results for v1.18/cke
  v1.18/cke/PRODUCT.yaml
  v1.18/cke/README.md
  v1.18/cke/e2e.log
  v1.18/cke/junit_01.xml
  v1.18/cke/sonobuoy.tar.gz
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1156 Conformance test results for v1.18/aks
  v1.18/aks/PRODUCT.yaml
  v1.18/aks/README.md
  v1.18/aks/e2e.log
  v1.18/aks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1155 Conformance test results for v1.19/aks
  v1.19/aks/PRODUCT.yaml
  v1.19/aks/README.md
  v1.19/aks/e2e.log
  v1.19/aks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1158 Conformance test results for v1.19/aks-engine
  v1.19/aks-engine/PRODUCT.yaml
  v1.19/aks-engine/README.md
  v1.19/aks-engine/e2e.log
  v1.19/aks-engine/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1151 Conformance test results for v1.18/rke-government
  v1.18/rke-government/PRODUCT.yaml
  v1.18/rke-government/README.md
  v1.18/rke-government/e2e.log
  v1.18/rke-government/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1159 Conformance results for v1.19/vmware-tanzu-kubernetes-grid
  v1.19/vmware-tanzu-kubernetes-grid/PRODUCT.yaml
  v1.19/vmware-tanzu-kubernetes-grid/README.md
  v1.19/vmware-tanzu-kubernetes-grid/e2e.log
  v1.19/vmware-tanzu-kubernetes-grid/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1160 Conformance tests for MicroK8s v1.19
  v1.19/microk8s/PRODUCT.yaml
  v1.19/microk8s/README.md
  v1.19/microk8s/e2e.log
  v1.19/microk8s/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1161 New conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/README.md
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1162 New conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/README.md
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1144 Conformance results for dce-4.0.2 on Oracle Linux Server 8.2 with Kubernetes:1.18.6
  v1.18/daocloud-1.18.6/PRODUCT.yaml
  v1.18/daocloud-1.18.6/README.md
  v1.18/daocloud-1.18.6/e2e.log
  v1.18/daocloud-1.18.6/junit_01.xml
Labels: not-verifiable

#1163 Clarify requirement for participation in program
  faq.md
Labels: not-verifiable

#1164 v1.18: add EKS conformance test results
  v1.18/eks/PRODUCT.yaml
  v1.18/eks/README.md
  v1.18/eks/e2e.log
  v1.18/eks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1166 v1.18: GKE conformance results
  v1.18/gke/PRODUCT.yaml
  v1.18/gke/README.md
  v1.18/gke/e2e.log
  v1.18/gke/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1143 Conformance results for v1.19/symplegma
  v1.19/symplegma/PRODUCT.yaml
  v1.19/symplegma/README.md
  v1.19/symplegma/e2e.log
  v1.19/symplegma/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1173 Conformance results for v1.18/ido-openness
  v1.18/ido-openness/PRODUCT.yaml
  v1.18/ido-openness/README.md
  v1.18/ido-openness/e2e.log
  v1.18/ido-openness/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1172 Conformance results for v1.18/openness
  v1.18/openness/PRODUCT.yaml
  v1.18/openness/README.md
  v1.18/openness/e2e.log
  v1.18/openness/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1180 Update conformance results for v1.16/ibm-openshift
  v1.16/ibm-openshift/PRODUCT.yaml
  v1.16/ibm-openshift/e2e.log
  v1.16/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.16, tests-verified-v1.16

#1179 Update conformance results for v1.17/ibm-openshift
  v1.17/ibm-openshift/PRODUCT.yaml
  v1.17/ibm-openshift/e2e.log
  v1.17/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1178 Update conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1175 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1176 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1177 Updated conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1169 Conformance results for v1.17/Bizmicro Portal
  v1.17/kbsys_Bizmicro_Portal_New/PRODUCT.yaml
  v1.17/kbsys_Bizmicro_Portal_New/README.md
  v1.17/kbsys_Bizmicro_Portal_New/e2e.log
  v1.17/kbsys_Bizmicro_Portal_New/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1174 Conformance results for v1.17/mcs
  v1.17/mcs/PRODUCT.yaml
  v1.17/mcs/README.md
  v1.17/mcs/e2e.log
  v1.17/mcs/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1182 Conformance results for v1.19/digitalocean
  v1.19/digitalocean/PRODUCT.yaml
  v1.19/digitalocean/README.md
  v1.19/digitalocean/e2e.log
  v1.19/digitalocean/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1181 Conformance results for v1.19/asuscloudinfra
  v1.19/asuscloudinfra/PRODUCT.yaml
Labels: not-verifiable

#1184 Conformance results for v1.19/k8s-tew
  v1.19/k8s-tew/PRODUCT.yaml
  v1.19/k8s-tew/README.md
  v1.19/k8s-tew/e2e.log
  v1.19/k8s-tew/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1183 Conformance results for v1.18/k8s-tew
  v1.18/k8s-tew/PRODUCT.yaml
  v1.18/k8s-tew/README.md
  v1.18/k8s-tew/e2e.log
  v1.18/k8s-tew/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1185 Conformance results for v1.19/openshift-dedicated
  v1.19/openshift-dedicated/PRODUCT.yaml
  v1.19/openshift-dedicated/README.md
  v1.19/openshift-dedicated/e2e.log
  v1.19/openshift-dedicated/junit_01.xml
Labels: release-documents-checked, release-v1.19, required-tests-missing
