Repository cncf/k8s-conformance, pull requests merged in 2021-05, with the labels that each got.

#1383 Conformance results for v1.18/LIMA version 0.4.0 beta
  v1.18/LIMA/202103231009_sonobuoy_e3bb3428-5e48-45f3-a694-a19c714dc0fd.tar.gz
  v1.18/LIMA/PRODUCT.yaml
  v1.18/LIMA/README.md
  v1.18/LIMA/e2e.log
  v1.18/LIMA/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1349 Conformance results for v1.18/QFusion
  v1.18/qfusion/PRODUCT.yaml
  v1.18/qfusion/README.md
  v1.18/qfusion/e2e.log
  v1.18/qfusion/junit_01.xml
Labels: not-verifiable

#1390 Conformance results for v1.20/weave-kubernetes-platform
  v1.20/weave-kubernetes-platform/PRODUCT.yaml
  v1.20/weave-kubernetes-platform/README.md
  v1.20/weave-kubernetes-platform/e2e.log
  v1.20/weave-kubernetes-platform/junit_01.xml
Labels: evidence-missing, no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1387 Conformance results for v1.20/ericsson-ccd
  v1.20/ericsson-ccd/PRODUCT.YAML
  v1.20/ericsson-ccd/README.md
  v1.20/ericsson-ccd/e2e.log
  v1.20/ericsson-ccd/junit_01.xml
Labels: not-verifiable

#1389 Conformance results for v1.20/KubeOperator
  v1.20/kubeoperator/PRODUCT.yaml
  v1.20/kubeoperator/README.md
  v1.20/kubeoperator/cluster.png
  v1.20/kubeoperator/e2e.log
  v1.20/kubeoperator/junit_01.xml
  v1.20/kubeoperator/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1391 Conformance results for v1.20/mcs
  v1.20/mcs/PRODUCT.yaml
  v1.20/mcs/README.md
  v1.20/mcs/e2e.log
  v1.20/mcs/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1344 Conformance results for v1.18/CloudControl AppZ Platform
  v1.18/CloudControl/PRODUCT.yaml
  v1.18/CloudControl/READEME.md
  v1.18/CloudControl/e2e.log
  v1.18/CloudControl/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1392 Conformance results for v1.20/catalyst-cloud
  v1.20/catalyst-cloud/PRODUCT.yaml
  v1.20/catalyst-cloud/README.txt
  v1.20/catalyst-cloud/e2e.log
  v1.20/catalyst-cloud/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1393 Conformance results for v1.20/kublr
  v1.20/kublr/PRODUCT.yaml
  v1.20/kublr/README.md
  v1.20/kublr/e2e.log
  v1.20/kublr/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1394 Conformance results for v1.19/nifcloud-kubernetes-service-hatoba
  v1.19/nifcloud-kubernetes-service-hatoba/PRODUCT.yaml
  v1.19/nifcloud-kubernetes-service-hatoba/README.md
  v1.19/nifcloud-kubernetes-service-hatoba/e2e.log
  v1.19/nifcloud-kubernetes-service-hatoba/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1395 Conformance results for v1.20/nifcloud-kubernetes-service-hatoba
  v1.20/nifcloud-kubernetes-service-hatoba/PRODUCT.yaml
  v1.20/nifcloud-kubernetes-service-hatoba/README.md
  v1.20/nifcloud-kubernetes-service-hatoba/e2e.log
  v1.20/nifcloud-kubernetes-service-hatoba/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1396 Conformance results for v1.20/d2iq
  v1.20/konvoy/202104222039_sonobuoy_11a6714d-0a98-411e-8758-56cd36140d80.tar.gz
  v1.20/konvoy/PRODUCT.yaml
  v1.20/konvoy/README.md
  v1.20/konvoy/e2e.log
  v1.20/konvoy/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1398 Conformance results for v1.21/kubeasz
  v1.21/kubeasz/PRODUCT.yaml
  v1.21/kubeasz/README.md
  v1.21/kubeasz/e2e.log
  v1.21/kubeasz/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1399 Conformance results for v1.19/gec-imke - v1.19.4
  v1.19/gec-imke/PRODUCT.yaml
  v1.19/gec-imke/README.md
  v1.19/gec-imke/e2e.log
  v1.19/gec-imke/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1400 Conformance results for v1.21/talos
  v1.21/talos/PRODUCT.yaml
  v1.21/talos/README.md
  v1.21/talos/e2e.log
  v1.21/talos/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1406 Conformance test results for v1.21/MicroK8s
  v1.21/microk8s/PRODUCT.yaml
  v1.21/microk8s/README.md
  v1.21/microk8s/e2e.log
  v1.21/microk8s/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1409 Conformance results for v1.21/symplegma
  v1.21/symplegma/PRODUCT.yaml
  v1.21/symplegma/README.md
  v1.21/symplegma/e2e.log
  v1.21/symplegma/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1411 Conformance results for v1.21/cdk
  v1.21/cdk/PRODUCT.yaml
  v1.21/cdk/README.md
  v1.21/cdk/e2e.log
  v1.21/cdk/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1410 Conformance results for v1.20/cdk
  v1.20/cdk/PRODUCT.yaml
  v1.20/cdk/README.md
  v1.20/cdk/e2e.log
  v1.20/cdk/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1401 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1402 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1404 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1414 Add README.md with script to create KubeConformance documents
  docs/README.md
  docs/gen-conformance-release-docs.sh
Labels: not-verifiable

#1413 Update README-WG.md
  README-WG.md
Labels: not-verifiable

#1287 Change Mirantis Docker Enterprise naming to Mirantis Kubernetes Engine
  mirantis-docker-enterprise/PRODUCT.yaml
  mirantis-docker-enterprise/README.md
  mirantis-docker-enterprise/e2e.log
  mirantis-docker-enterprise/junit_01.xml
Labels: not-verifiable

#1415 Fix v1.21 and move typhoon results to v1.21/typhoon
  v1.21/typhoon/PRODUCT.yaml
  v1.21/typhoon/README.md
  v1.21/typhoon/e2e.log
  v1.21/typhoon/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1417 Conformance reults for v1.20/gec-imke
  v1.20/gec-imke/PRODUCT.yaml
  v1.20/gec-imke/README.md
  v1.20/gec-imke/e2e.log
  v1.20/gec-imke/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1416 Conformance results for v1.20/TencentCloud
  v1.20/tencentcloud/CreateTkeCluster.png
  v1.20/tencentcloud/PRODUCT.yaml
  v1.20/tencentcloud/README.md
  v1.20/tencentcloud/e2e.log
  v1.20/tencentcloud/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1419 Conformance results for v1.19/stackit-kubernetes-engine
  v1.19/stackit-kubernetes-engine/README.md
  v1.19/stackit-kubernetes-engine/e2e.log
  v1.19/stackit-kubernetes-engine/junit_01.xml
  v1.19/stackit-kubernetes-engine/product.yaml
Labels: not-verifiable

#1420 Conformance results for v1.19/KubeSphere
  v1.19/KubeSphere/PRODUCT.yaml
  v1.19/KubeSphere/README.md
  v1.19/KubeSphere/e2e.log
  v1.19/KubeSphere/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1421 Conformance results for v1.20/ido-openness
  v1.20/ido-openness/PRODUCT.yaml
  v1.20/ido-openness/README.md
  v1.20/ido-openness/e2e.log
  v1.20/ido-openness/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1422 Conformance results for v1.20/openness
  v1.20/openness/PRODUCT.yaml
  v1.20/openness/README.md
  v1.20/openness/e2e.log
  v1.20/openness/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1423 Conformance results for v1.20/giantswarm-aws
  v1.20/giantswarm-aws/PRODUCT.yaml
  v1.20/giantswarm-aws/README.md
  v1.20/giantswarm-aws/e2e.log
  v1.20/giantswarm-aws/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1408 Generate conformance release documentation for 1.16-21
  docs/KubeConformance-1.16.md
  docs/KubeConformance-1.17.md
  docs/KubeConformance-1.18.md
  docs/KubeConformance-1.19.md
  docs/KubeConformance-1.20.md
  docs/KubeConformance-1.21.md
Labels: not-verifiable

#1412 Conformance results for v1.19/cloudboostr
  v1.19/cloudboostr/PRODUCT.yaml
  v1.19/cloudboostr/README.md
  v1.19/cloudboostr/e2e.log
  v1.19/cloudboostr/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1418 Conformance results for v1.20 OpenShift (4.7.0)
  v1.19/openshift/README.md
  v1.20/openshift/PRODUCT.yaml
  v1.20/openshift/README.md
  v1.20/openshift/e2e.log
  v1.20/openshift/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1424 Conformance results for v1.20/kubekey
  v1.20/kubekey/PRODUCT.yaml
  v1.20/kubekey/README.md
  v1.20/kubekey/e2e.log
  v1.20/kubekey/junit_01.xml
  v1.20/kubekey/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1425 Conformance results for v1.20/kOps
  v1.20/kops/PRODUCT.yaml
  v1.20/kops/README.md
  v1.20/kops/e2e.log
  v1.20/kops/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1429 Conformance results for v1.19/giantswarm-kvm
  v1.19/giantswarm-kvm/PRODUCT.yaml
  v1.19/giantswarm-kvm/README.md
  v1.19/giantswarm-kvm/e2e.log
  v1.19/giantswarm-kvm/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1430 Conformance reults for v1.21/SamsungSDS-Kubernetes-Service
  v1.21/SamsungSDS-Kubernetes-Service/PRODUCT.yaml
  v1.21/SamsungSDS-Kubernetes-Service/README.md
  v1.21/SamsungSDS-Kubernetes-Service/e2e.log
  v1.21/SamsungSDS-Kubernetes-Service/junit_01.xml
Labels: not-verifiable

#1432 EKS v1.20 conformance results
  v1.20/eks/PRODUCT.yaml
  v1.20/eks/README.md
  v1.20/eks/e2e.log
  v1.20/eks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1437 Conformance results for v1.19/kubespray
  v1.19/kubespray/PRODUCT.yaml
  v1.19/kubespray/README.md
  v1.19/kubespray/e2e.log
  v1.19/kubespray/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1441 Conformance results for v1.19/ridge
  v1.19/ridge/PRODUCT.yaml
  v1.19/ridge/README.md
  v1.19/ridge/e2e.log
  v1.19/ridge/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1459 Conformance results for v1.19/spectrocloud
  v1.19/spectrocloud/PRODUCT.yaml
  v1.19/spectrocloud/README.md
  v1.19/spectrocloud/e2e.log
  v1.19/spectrocloud/junit_01.xml
  v1.19/spectrocloud/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1461 Conformance results for v1.19/nirmata
  v1.19/nirmata/PRODUCT.yaml
  v1.19/nirmata/README.md
  v1.19/nirmata/e2e.log
  v1.19/nirmata/junit_01.xml
  v1.20/nirmata/PRODUCT.yaml
  v19
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1474 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1476 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1478 Conformance results for v1.19/MetalK8s
  v1.19/MetalK8s/PRODUCT.yaml
  v1.19/MetalK8s/README.md
  v1.19/MetalK8s/e2e.log
  v1.19/MetalK8s/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1438 Conformance results for v1.20/nexastack
  v1.20/nexastack/PRODUCT.yaml
  v1.20/nexastack/Please_DocuSign_Certified_Kubernetes_Form.pd.pdf
  v1.20/nexastack/README.md
  v1.20/nexastack/e2e.log
  v1.20/nexastack/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1439 Conformance results for v1.20/lstack
  v1.20/lstack/PRODUCT.yaml
  v1.20/lstack/README.MD
  v1.20/lstack/cluster.png
  v1.20/lstack/e2e.log
  v1.20/lstack/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1443 Conformance results for v1.20/olcne
  v1.20/olcne/PRODUCT.yaml
  v1.20/olcne/README.md
  v1.20/olcne/e2e.log
  v1.20/olcne/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1444 Conformance results for v1.20/ridge
  v1.20/ridge/PRODUCT.yaml
  v1.20/ridge/README.md
  v1.20/ridge/e2e.log
  v1.20/ridge/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1460 Conformance results for v1.20/spectrocloud
  v1.20/spectrocloud/PRODUCT.yaml
  v1.20/spectrocloud/README.md
  v1.20/spectrocloud/e2e.log
  v1.20/spectrocloud/junit_01.xml
  v1.20/spectrocloud/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1462 Conformance results for v1.20/acornsoft-cocktail
  v1.20/acornsoft-cocktail/PRODUCT.yaml
  v1.20/acornsoft-cocktail/README.md
  v1.20/acornsoft-cocktail/e2e.log
  v1.20/acornsoft-cocktail/junit_01.xml
  v1.20/acornsoft-cocktail/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1463 Conformance results for v1.20/dce
  README.md
  v1.20/daocloud/PRODUCT.yaml
  v1.20/daocloud/README.md
  v1.20/daocloud/e2e.log
  v1.20/daocloud/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1470 Conformance results for v1.19/Intersight-Kubernetes-Service
  v1.19/Intersight-Kubernetes-Service/PRODUCT.yaml
  v1.19/Intersight-Kubernetes-Service/README.md
  v1.19/Intersight-Kubernetes-Service/e2e.log
  v1.19/Intersight-Kubernetes-Service/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1465 Conformance results for v1.21/flexkube
  v1.21/flexkube/PRODUCT.yaml
  v1.21/flexkube/README.md
  v1.21/flexkube/e2e.log
  v1.21/flexkube/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1467 Conformance test results for LKE v1.21
  v1.21/lke/PRODUCT.yaml
  v1.21/lke/README.md
  v1.21/lke/e2e.log
  v1.21/lke/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1471 Conformance results for v1.21/ebaocloud and insuremo
  v1.21/ebaocloud/PRODUCT.yaml
  v1.21/ebaocloud/README.md
  v1.21/ebaocloud/e2e.log
  v1.21/ebaocloud/junit_01.xml
  v1.21/insuremo/PRODUCT.yaml
  v1.21/insuremo/README.md
  v1.21/insuremo/e2e.log
  v1.21/insuremo/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1472 Conformance results for v1.21/ventus
  v1.21/ventus/PRODUCT.yaml
  v1.21/ventus/README.md
  v1.21/ventus/e2e.log
  v1.21/ventus/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1473 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1480 Conformance results for v1.21/opennebula-kubernetes-appliance
  v1.21/opennebula-kubernetes-appliance/PRODUCT.yaml
  v1.21/opennebula-kubernetes-appliance/README.md
  v1.21/opennebula-kubernetes-appliance/e2e.log
  v1.21/opennebula-kubernetes-appliance/junit_01.xml
  v1.21/opennebula-kubernetes-appliance/sonobuoy.tar.gz
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1483 Conformance results for v1.20/MetalK8s
  v1.20/MetalK8s/PRODUCT.yaml
  v1.20/MetalK8s/README.md
  v1.20/MetalK8s/e2e.log
  v1.20/MetalK8s/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1484 Conformance results for v1.21/MetalK8s
  v1.21/MetalK8s/PRODUCT.yaml
  v1.21/MetalK8s/README.md
  v1.21/MetalK8s/e2e.log
  v1.21/MetalK8s/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1485 Conformance results for v1.21/Harmonycloud
  v1.21/harmonycloud/PRODUCT.yaml
  v1.21/harmonycloud/README.md
  v1.21/harmonycloud/e2e.log
  v1.21/harmonycloud/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1486 Conformance results for v1.21/Harmonycloud-Installer
  v1.21/harmonycloud-Installer/PRODUCT.yaml
  v1.21/harmonycloud-Installer/README.md
  v1.21/harmonycloud-Installer/e2e.log
  v1.21/harmonycloud-Installer/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1487 Conformance results for v1.20/kubespray
  v1.20/kubespray/PRODUCT.yaml
  v1.20/kubespray/README.md
  v1.20/kubespray/e2e.log
  v1.20/kubespray/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20
