Repository cncf/k8s-conformance, pull requests merged in 2021-06, with the labels that each got.

#1482 Conformance results for v1.20/snaps-kubernetes
  v1.20/snaps-kubernetes/PRODUCT.yaml
  v1.20/snaps-kubernetes/README.md
  v1.20/snaps-kubernetes/e2e.log
  v1.20/snaps-kubernetes/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1469 Conformance results for v1.21/kind
  v1.21/kind/PRODUCT.yaml
  v1.21/kind/README.md
  v1.21/kind/e2e.log
  v1.21/kind/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1488 TKGI / PKS 1.11 conformance with Kubernetes v1.20
  v1.20/pks/PRODUCT.yaml
  v1.20/pks/README.md
  v1.20/pks/e2e.log
  v1.20/pks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1489 Conformance results for v1.19/aks-engine-azurestack
  v1.19/aks-engine-azurestack/PRODUCT.yaml
  v1.19/aks-engine-azurestack/README.md
  v1.19/aks-engine-azurestack/e2e.log
  v1.19/aks-engine-azurestack/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1490 Conformance results for v1.20/aks-engine-azurestack
  v1.20/aks-engine-azurestack/PRODUCT.yaml
  v1.20/aks-engine-azurestack/README.md
  v1.20/aks-engine-azurestack/e2e.log
  v1.20/aks-engine-azurestack/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1492 Conformance results for v1.20/platform9
  v1.20/platform9/PRODUCT.yaml
  v1.20/platform9/README.md
  v1.20/platform9/e2e.log
  v1.20/platform9/junit_01.xml
  v1.20/platform9/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1494 Conformance results for v1.21/k0s v1.21.1+k0s.0
  v1.21/k0s/PRODUCT.yaml
  v1.21/k0s/README.md
  v1.21/k0s/e2e.log
  v1.21/k0s/junit_01.xml
  v1.21/k0s/sonobuoy_results.tar.gz
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1495 Add conformance results for v1.21/fury
  v1.21/fury-distribution/PRODUCT.yaml
  v1.21/fury-distribution/README.md
  v1.21/fury-distribution/e2e.log
  v1.21/fury-distribution/junit_01.xml
  v1.21/fury-distribution/sonobuoy.tar.gz
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1496 Update conformance results for v1.20/fury
  v1.20/fury-distribution/PRODUCT.yaml
  v1.20/fury-distribution/README.md
  v1.20/fury-distribution/e2e.log
  v1.20/fury-distribution/junit_01.xml
  v1.20/fury-distribution/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1497 Conformance test results for v1.21/k3s
  v1.21/k3s/PRODUCT.yaml
  v1.21/k3s/README.md
  v1.21/k3s/e2e.log
  v1.21/k3s/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1498 Update conformance results for v1.19/fury
  v1.19/fury-distribution/PRODUCT.yaml
  v1.19/fury-distribution/README.md
  v1.19/fury-distribution/e2e.log
  v1.19/fury-distribution/junit_01.xml
  v1.19/fury-distribution/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1499 EKS-D v1.19 conformance
  v1.19/eks-d/PRODUCT.yaml
  v1.19/eks-d/README.md
  v1.19/eks-d/e2e.log
  v1.19/eks-d/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1500 EKS-D v1.20 conformance
  v1.20/eks-d/PRODUCT.yaml
  v1.20/eks-d/README.md
  v1.20/eks-d/e2e.log
  v1.20/eks-d/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1502 New conformance results for IKS v1.21
  v1.21/iks/PRODUCT.yaml
  v1.21/iks/README.md
  v1.21/iks/e2e.log
  v1.21/iks/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1503 New conformance results for v1.20/ibm-openshift
  v1.20/ibm-openshift/PRODUCT.yaml
  v1.20/ibm-openshift/README.md
  v1.20/ibm-openshift/e2e.log
  v1.20/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1504 Here are the Kubernetes v1.19.8 conformance test results from a QingC…
  v1.19/QKE/PRODUCT.yaml
  v1.19/QKE/QingCloudLogo.ai
  v1.19/QKE/README.md
  v1.19/QKE/e2e.log
  v1.19/QKE/guide1.png
  v1.19/QKE/guide2.png
  v1.19/QKE/guide3.png
  v1.19/QKE/guide4.png
  v1.19/QKE/guide5.png
  v1.19/QKE/guide6.png
  v1.19/QKE/guide7.png
  v1.19/QKE/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1501 Conformance results for v1.21/chinamobile-cmit-paas
  v1.21/chinamobile-cmit-paas/PRODUCT.yaml
  v1.21/chinamobile-cmit-paas/README.md
  v1.21/chinamobile-cmit-paas/e2e.log
  v1.21/chinamobile-cmit-paas/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1491 Conformance results for v1.20/vcluster
  v1.20/vcluster/PRODUCT.yaml
  v1.20/vcluster/README.md
  v1.20/vcluster/e2e.log
  v1.20/vcluster/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1493 Conformance results for v1.20/cke
  v1.20/cke/PRODUCT.yaml
  v1.20/cke/README.md
  v1.20/cke/e2e.log
  v1.20/cke/junit_01.xml
  v1.20/cke/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1505 Conformance results for v1.20/agorakube
  v1.20/agorakube/PRODUCT.yaml
  v1.20/agorakube/README.md
  v1.20/agorakube/e2e.log
  v1.20/agorakube/junit_01.xml
  v1.20/agorakube/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1506 Airship-Conformancev1.19
  v1.19/airship/PRODUCT.yaml
  v1.19/airship/README.md
  v1.19/airship/e2e.log
  v1.19/airship/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1508 Nutanix Karbon k8s v1.20 conformance
  v1.20/ntnx-karbon/PRODUCT.yaml
  v1.20/ntnx-karbon/README.md
  v1.20/ntnx-karbon/e2e.log
  v1.20/ntnx-karbon/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1511 Conformance Results for Rafay v1.19
  rafay/PRODUCT.yaml
  rafay/README.md
  rafay/Rafay_Logo.png
  rafay/Rafay_Logo.svg
  rafay/e2e.log
  rafay/junit_01.xml
  v1.19/rafay/PRODUCT.yaml
  v1.19/rafay/README.md
  v1.19/rafay/Rafay_Logo.png
  v1.19/rafay/Rafay_Logo.svg
  v1.19/rafay/e2e.log
  v1.19/rafay/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19
