Repository cncf/k8s-conformance, pull requests merged in 2021-02, with the labels that each got.

#1298 Conformance results for v1.18/ridge
  v1.18/ridge/PRODUCT.yaml
  v1.18/ridge/README.md
  v1.18/ridge/e2e.log
  v1.18/ridge/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1309 Conformance results for v1.19/giantswarm-azure
  v1.19/giantswarm-azure/PRODUCT.yaml
  v1.19/giantswarm-azure/README.md
  v1.19/giantswarm-azure/e2e.log
  v1.19/giantswarm-azure/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1307 Kops v1.19 conformance
  v1.19/kops/PRODUCT.yaml
  v1.19/kops/README.md
  v1.19/kops/e2e.log
  v1.19/kops/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1304 Conformance results for v1.19/Diamanti-Spektra
  v1.19/Diamanti-Spektra/PRODUCT.yaml
  v1.19/Diamanti-Spektra/README.md
  v1.19/Diamanti-Spektra/e2e.log
  v1.19/Diamanti-Spektra/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1311 Conformance results for v1.19/acp
  v1.19/acp/PRODUCT.yaml
  v1.19/acp/README.md
  v1.19/acp/e2e.log
  v1.19/acp/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1314 Conformance results for v1.19/openstack-magnum
  v1.19/openstack-magnum/PRODUCT.yaml
  v1.19/openstack-magnum/README.md
  v1.19/openstack-magnum/e2e.log
  v1.19/openstack-magnum/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1317 Conformance results for v1.19/catalyst-cloud
  v1.19/catalyst-cloud/PRODUCT.yaml
  v1.19/catalyst-cloud/README.txt
  v1.19/catalyst-cloud/e2e.log
  v1.19/catalyst-cloud/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1319 Conformance results for v1.19/ido-openness
  v1.19/ido-openness/PRODUCT.yaml
  v1.19/ido-openness/README.md
  v1.19/ido-openness/e2e.log
  v1.19/ido-openness/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1318 Conformance results for v1.19/openness
  v1.19/openness/PRODUCT.yaml
  v1.19/openness/README.md
  v1.19/openness/e2e.log
  v1.19/openness/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1321 Conformance results for v1.17/kubermatic
  v1.17/kubermatic/PRODUCT.yaml
  v1.17/kubermatic/e2e.log
  v1.17/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1323 Conformance results for v1.18/kubermatic
  v1.18/kubermatic/PRODUCT.yaml
  v1.18/kubermatic/e2e.log
  v1.18/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1324 Conformance results for v1.19/kubermatic
  v1.19/kubermatic/PRODUCT.yaml
  v1.19/kubermatic/e2e.log
  v1.19/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1325 Conformance results for v1.19/gke
  v1.19/gke/PRODUCT.yaml
  v1.19/gke/README.md
  v1.19/gke/e2e.log
  v1.19/gke/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1322 Conformance results for v1.20/kubermatic
  v1.20/kubermatic/PRODUCT.yaml
  v1.20/kubermatic/README.md
  v1.20/kubermatic/e2e.log
  v1.20/kubermatic/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1331 Conformance results for v1.18/nexastack
  v1.18/nexastack/PRODUCT.yaml
  v1.18/nexastack/Please_DocuSign_Certified_Kubernetes_Form.pd.pdf
  v1.18/nexastack/README.md
  v1.18/nexastack/e2e.log
  v1.18/nexastack/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1308 Conformance results for v1.20/digitalocean
  v1.20/digitalocean/PRODUCT.yaml
  v1.20/digitalocean/README.md
  v1.20/digitalocean/e2e.log
  v1.20/digitalocean/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1310 Conformance results for v1.20/k0s v0.10.0
  v1.20/k0s/PRODUCT.yaml
  v1.20/k0s/README.md
  v1.20/k0s/e2e.log
  v1.20/k0s/junit_01.xml
  v1.20/k0s/sonobuoy_results.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1320 Conformance results for v1.20/openstack-magnum
  v1.20/openstack-magnum/PRODUCT.yaml
  v1.20/openstack-magnum/README.md
  v1.20/openstack-magnum/e2e.log
  v1.20/openstack-magnum/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1327 New conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/README.md
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1328 New conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/README.md
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1329 Conformance results for v1.19/ELASTX
  v1.19/elastx/PRODUCT.yaml
  v1.19/elastx/README.md
  v1.19/elastx/e2e.log
  v1.19/elastx/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1330 RKE v1.20 conformance results
  v1.20/rke/PRODUCT.yaml
  v1.20/rke/README.md
  v1.20/rke/e2e.log
  v1.20/rke/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1332 rancher v1.20 conformance results
  v1.20/rancher/PRODUCT.yaml
  v1.20/rancher/README.md
  v1.20/rancher/e2e.log
  v1.20/rancher/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1333 EKS v1.19 conformance results
  v1.19/eks/PRODUCT.yaml
  v1.19/eks/README.md
  v1.19/eks/e2e.log
  v1.19/eks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1335 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1336 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1337 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1339 Update conformance results for v1.17/ibm-openshift
  v1.17/ibm-openshift/PRODUCT.yaml
  v1.17/ibm-openshift/e2e.log
  v1.17/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1338 Update conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1340 Conformance results for v1.19/ntnx-karbon
  v1.19/ntnx-karbon/PRODUCT.yaml
  v1.19/ntnx-karbon/README.md
  v1.19/ntnx-karbon/e2e.log
  v1.19/ntnx-karbon/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1341 Conformance results for v1.20/ovh
  v1.20/ovh/PRODUCT.yaml
  v1.20/ovh/README.md
  v1.20/ovh/e2e.log
  v1.20/ovh/junit_01.xml
  v1.20/ovh/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1342 Conformance results for v1.20/kube-up-gce
  v1.20/kube-up-gce/PRODUCT.yaml
  v1.20/kube-up-gce/README.md
  v1.20/kube-up-gce/e2e.log
  v1.20/kube-up-gce/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20
