Repository cncf/k8s-conformance, pull requests merged in 2021-01, with the labels that each got.

#1263 Conformance results for v1.18/metakube
  v1.18/metakube-aws/PRODUCT.yaml
  v1.18/metakube-aws/README.md
  v1.18/metakube-aws/e2e.log
  v1.18/metakube-aws/junit_01.xml
  v1.18/metakube-openstack/PRODUCT.yaml
  v1.18/metakube-openstack/README.md
  v1.18/metakube-openstack/e2e.log
  v1.18/metakube-openstack/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1275 Conformance test results for v1.20/MicroK8s
  v1.20/microk8s/PRODUCT.yaml
  v1.20/microk8s/README.md
  v1.20/microk8s/e2e.log
  v1.20/microk8s/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1277 Add k8s v1.20 conformance test for minikube
  v1.20/minikube/PRODUCT.yaml
  v1.20/minikube/README.md
  v1.20/minikube/e2e.log
  v1.20/minikube/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1279 Conformance results for v1.19/fury-distribution
  v1.19/fury-distribution/PRODUCT.yaml
  v1.19/fury-distribution/README.md
  v1.19/fury-distribution/e2e.log
  v1.19/fury-distribution/junit_01.xml
  v1.19/fury-distribution/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1280 Conformance results for v1.20/fury-distribution
  v1.20/fury-distribution/PRODUCT.yaml
  v1.20/fury-distribution/README.md
  v1.20/fury-distribution/e2e.log
  v1.20/fury-distribution/junit_01.xml
  v1.20/fury-distribution/sonobuoy.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1283 Updated conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1281 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1282 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1285 Update conformance results for v1.17/ibm-openshift
  v1.17/ibm-openshift/PRODUCT.yaml
  v1.17/ibm-openshift/e2e.log
  v1.17/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1284 Update conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1278 Conformance results for v1.19/HyperCloud
  v1.19/HyperCloud/PRODUCT.yaml
  v1.19/HyperCloud/README.md
  v1.19/HyperCloud/e2e.log
  v1.19/HyperCloud/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1286 Conformance results for v1.19/lokomotive
  v1.19/lokomotive/PRODUCT.yaml
  v1.19/lokomotive/README.md
  v1.19/lokomotive/e2e.log
  v1.19/lokomotive/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1276 Make commands copy pastable
  instructions.md
Labels: not-verifiable

#1270 Conformance test results for v1.19/rke-government
  v1.19/rke-government/PRODUCT.yaml
  v1.19/rke-government/README.md
  v1.19/rke-government/e2e.log
  v1.19/rke-government/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1291 Conformance Results for v1.20/Gardener
  v1.20/gardener-aws/PRODUCT.yaml
  v1.20/gardener-aws/README.md
  v1.20/gardener-aws/e2e.log
  v1.20/gardener-aws/junit_01.xml
  v1.20/gardener-gcp/PRODUCT.yaml
  v1.20/gardener-gcp/README.md
  v1.20/gardener-gcp/e2e.log
  v1.20/gardener-gcp/junit_01.xml
  v1.20/gardener-openstack/PRODUCT.yaml
  v1.20/gardener-openstack/README.md
  v1.20/gardener-openstack/e2e.log
  v1.20/gardener-openstack/junit_01.xml
  v1.20/sap-cp-aws/PRODUCT.yaml
  v1.20/sap-cp-aws/README.md
  v1.20/sap-cp-aws/e2e.log
  v1.20/sap-cp-aws/junit_01.xml
  v1.20/sap-cp-gcp/PRODUCT.yaml
  v1.20/sap-cp-gcp/README.md
  v1.20/sap-cp-gcp/e2e.log
  v1.20/sap-cp-gcp/junit_01.xml
  v1.20/sap-cp-openstack/PRODUCT.yaml
  v1.20/sap-cp-openstack/README.md
  v1.20/sap-cp-openstack/e2e.log
  v1.20/sap-cp-openstack/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1292 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1293 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1294 Updated conformance results for IKS v1.17
  v1.17/iks/PRODUCT.yaml
  v1.17/iks/e2e.log
  v1.17/iks/junit_01.xml
Labels: no-failed-tests-v1.17, release-documents-checked, release-v1.17, tests-verified-v1.17

#1296 Conformance tests results for v1.19/lke
  v1.19/lke/PRODUCT.yaml
  v1.19/lke/README.md
  v1.19/lke/e2e.log
  v1.19/lke/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1290 Conformance results for v1.18/swisscom-kubernetes-service
  v1.18/swisscom-kubernetes-service/PRODUCT.yaml
  v1.18/swisscom-kubernetes-service/README.md
  v1.18/swisscom-kubernetes-service/e2e.log
  v1.18/swisscom-kubernetes-service/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1299 Conformance results of IBM Cloud Private for v1.19
  v1.19/icp/icp/PRODUCT.yaml
  v1.19/icp/icp/README.md
  v1.19/icp/icp/e2e.log
  v1.19/icp/icp/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1300 Conformance test result for v1.19.5 on UCloud Kubernetes Service
  v1.19/Ucloud/PRODUCT.yaml
  v1.19/Ucloud/e2e.log
  v1.19/Ucloud/junit_01.xml
  v1.19/Ucloud/readme.md
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1301 Conformance results for v1.19/cke
  v1.19/cke/PRODUCT.yaml
  v1.19/cke/README.md
  v1.19/cke/e2e.log
  v1.19/cke/junit_01.xml
  v1.19/cke/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1302 Conformance results for v1.19/giantswarm-aws
  v1.19/giantswarm-aws/PRODUCT.yaml
  v1.19/giantswarm-aws/README.md
  v1.19/giantswarm-aws/e2e.log
  v1.19/giantswarm-aws/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1305 TKGI / PKS 1.10 conformance with Kubernetes v1.19
  v1.19/pks/PRODUCT.yaml
  v1.19/pks/README.md
  v1.19/pks/e2e.log
  v1.19/pks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19
