Repository cncf/k8s-conformance, pull requests merged in 2021-08, with the labels that each got.

#1542 EKS v1.21 conformance results
  v1.21/eks/PRODUCT.yaml
  v1.21/eks/README.md
  v1.21/eks/e2e.log
  v1.21/eks/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1549 Updated conformance results for IKS v1.21
  v1.21/iks/PRODUCT.yaml
  v1.21/iks/e2e.log
  v1.21/iks/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1550 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1551 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1552 Update conformance results for v1.20/ibm-openshift
  v1.20/ibm-openshift/PRODUCT.yaml
  v1.20/ibm-openshift/e2e.log
  v1.20/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1553 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1554 Conformance results for v1.21/nifcloud-kubernetes-service-hatoba
  v1.21/nifcloud-kubernetes-service-hatoba/PRODUCT.yaml
  v1.21/nifcloud-kubernetes-service-hatoba/README.md
  v1.21/nifcloud-kubernetes-service-hatoba/e2e.log
  v1.21/nifcloud-kubernetes-service-hatoba/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1558 Conformance results for v1.19/deckhouse
  v1.19/deckhouse/PRODUCT.yaml
  v1.19/deckhouse/README.md
  v1.19/deckhouse/e2e.log
  v1.19/deckhouse/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1557 Conformance results for v1.20/deckhouse
  v1.20/deckhouse/PRODUCT.yaml
  v1.20/deckhouse/README.md
  v1.20/deckhouse/e2e.log
  v1.20/deckhouse/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1556 Conformance results for v1.21/deckhouse
  v1.21/deckhouse/PRODUCT.yaml
  v1.21/deckhouse/README.md
  v1.21/deckhouse/e2e.log
  v1.21/deckhouse/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1559 Conformance results for v1.20/oke
  v1.20/oke/PRODUCT.yaml
  v1.20/oke/README.md
  v1.20/oke/e2e.log
  v1.20/oke/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1545 Conformance Results for v1.21/kingsoft-container-engine
  v1.21/kingsoft-container-engine/PRODUCT.yaml
  v1.21/kingsoft-container-engine/README.md
  v1.21/kingsoft-container-engine/e2e.log
  v1.21/kingsoft-container-engine/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1547 Conformance Results for v1.21/gardener
  v1.20/gardener-alicloud/PRODUCT.yaml
  v1.20/gardener-alicloud/README.md
  v1.20/gardener-alicloud/e2e.log
  v1.20/gardener-alicloud/junit_01.xml
  v1.20/gardener-azure/PRODUCT.yaml
  v1.20/gardener-azure/README.md
  v1.20/gardener-azure/e2e.log
  v1.20/gardener-azure/junit_01.xml
  v1.21/gardener-alicloud/PRODUCT.yaml
  v1.21/gardener-alicloud/README.md
  v1.21/gardener-alicloud/e2e.log
  v1.21/gardener-alicloud/junit_01.xml
  v1.21/gardener-aws/PRODUCT.yaml
  v1.21/gardener-aws/README.md
  v1.21/gardener-aws/e2e.log
  v1.21/gardener-aws/junit_01.xml
  v1.21/gardener-azure/PRODUCT.yaml
  v1.21/gardener-azure/README.md
  v1.21/gardener-azure/e2e.log
  v1.21/gardener-azure/junit_01.xml
  v1.21/gardener-gcp/PRODUCT.yaml
  v1.21/gardener-gcp/README.md
  v1.21/gardener-gcp/e2e.log
  v1.21/gardener-gcp/junit_01.xml
  v1.21/gardener-openstack/PRODUCT.yaml
  v1.21/gardener-openstack/README.md
  v1.21/gardener-openstack/e2e.log
  v1.21/gardener-openstack/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1546 Conformance Results for v1.21/sap-cp
  v1.20/sap-cp-alicloud/PRODUCT.yaml
  v1.20/sap-cp-alicloud/README.md
  v1.20/sap-cp-alicloud/e2e.log
  v1.20/sap-cp-alicloud/junit_01.xml
  v1.20/sap-cp-azure/PRODUCT.yaml
  v1.20/sap-cp-azure/README.md
  v1.20/sap-cp-azure/e2e.log
  v1.20/sap-cp-azure/junit_01.xml
  v1.21/sap-cp-alicloud/PRODUCT.yaml
  v1.21/sap-cp-alicloud/README.md
  v1.21/sap-cp-alicloud/e2e.log
  v1.21/sap-cp-alicloud/junit_01.xml
  v1.21/sap-cp-aws/PRODUCT.yaml
  v1.21/sap-cp-aws/README.md
  v1.21/sap-cp-aws/e2e.log
  v1.21/sap-cp-aws/junit_01.xml
  v1.21/sap-cp-azure/PRODUCT.yaml
  v1.21/sap-cp-azure/README.md
  v1.21/sap-cp-azure/e2e.log
  v1.21/sap-cp-azure/junit_01.xml
  v1.21/sap-cp-gcp/PRODUCT.yaml
  v1.21/sap-cp-gcp/README.md
  v1.21/sap-cp-gcp/e2e.log
  v1.21/sap-cp-gcp/junit_01.xml
  v1.21/sap-cp-openstack/PRODUCT.yaml
  v1.21/sap-cp-openstack/README.md
  v1.21/sap-cp-openstack/e2e.log
  v1.21/sap-cp-openstack/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1543 Conformance results for v1.19.4/huawei nfv_fusionstage
  v1.19/huawei-nfv_fusionstage/PRODUCT.yaml
  v1.19/huawei-nfv_fusionstage/README.md
  v1.19/huawei-nfv_fusionstage/e2e.log
  v1.19/huawei-nfv_fusionstage/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1562 ADD Inspur ICKS conformance with k8s v1.20
  v1.20/inspur-incloud-amd64/PRODUCT.yaml
  v1.20/inspur-incloud-amd64/README.md
  v1.20/inspur-incloud-amd64/e2e.log
  v1.20/inspur-incloud-amd64/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1563 Conformance results for v1.21/kOps
  v1.21/kops/PRODUCT.yaml
  v1.21/kops/README.md
  v1.21/kops/e2e.log
  v1.21/kops/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1541 Conformance results for v1.19/taikun
  v1.19/taikun/PRODUCT.yaml
  v1.19/taikun/README.md
  v1.19/taikun/e2e.log
  v1.19/taikun/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1548 Conformance results for v1.20/taikun
  v1.20/taikun/PRODUCT.yaml
  v1.20/taikun/README.md
  v1.20/taikun/e2e.log
  v1.20/taikun/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1540 Conformance results for v1.19/dahua-MagicCube
  v1.19/dahua-MagicCube/1.png
  v1.19/dahua-MagicCube/2.png
  v1.19/dahua-MagicCube/3.png
  v1.19/dahua-MagicCube/4.png
  v1.19/dahua-MagicCube/PRODUCT.yaml
  v1.19/dahua-MagicCube/README.md
  v1.19/dahua-MagicCube/e2e.log
  v1.19/dahua-MagicCube/junit_01.xml
  v1.19/dahua-MagicCube/overallarch.bmp
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1566 Conformance results for v1.22/typhoon
  v1.22/typhoon/PRODUCT.yaml
  v1.22/typhoon/README.md
  v1.22/typhoon/e2e.log
  v1.22/typhoon/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1567 Conformance results for v1.22/scaleway
  v1.22/scaleway/PRODUCT.yaml
  v1.22/scaleway/README.yaml
  v1.22/scaleway/e2e.log
  v1.22/scaleway/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1569 Conformance results for v1.21/d2iq
  v1.21/konvoy/202108161923_sonobuoy_397a6bce-02f8-4f1a-bf88-61fc26c348df.tar.gz
  v1.21/konvoy/PRODUCT.yaml
  v1.21/konvoy/README.md
  v1.21/konvoy/e2e.log
  v1.21/konvoy/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1564 Conformance results for v1.20/ecloud
  v1.20/ecloud/PRODUCT.yaml
  v1.20/ecloud/README.md
  v1.20/ecloud/e2e.log
  v1.20/ecloud/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1565 Conformance results for v1.21/robin.io
  v1.21/robin.io/PRODUCT.yaml
  v1.21/robin.io/README.md
  v1.21/robin.io/e2e.log
  v1.21/robin.io/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1568 Conformance results for v1.20/tenxcloud
  v1.20/tenxcloud/PRODUCT.yaml
  v1.20/tenxcloud/README.md
  v1.20/tenxcloud/e2e.log
  v1.20/tenxcloud/junit_01.xml
  v1.20/tenxcloud/version.txt
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20
