Repository cncf/k8s-conformance, pull requests merged in 2021-04, with the labels that each got.

#1346 Conformance tests results for v1.20 LKE
  v1.20/lke/PRODUCT.yaml
  v1.20/lke/README.md
  v1.20/lke/e2e.log
  v1.20/lke/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1345 Conformance results for v1.20/k0s v0.11.0
  v1.20/k0s/PRODUCT.yaml
  v1.20/k0s/README.md
  v1.20/k0s/e2e.log
  v1.20/k0s/junit_01.xml
  v1.20/k0s/sonobuoy_results.tar.gz
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1347 Conformance results for v1.20/gke
  v1.20/gke/PRODUCT.yaml
  v1.20/gke/README.md
  v1.20/gke/e2e.log
  v1.20/gke/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1350 Conformance results for v1.20/openshift-dedicated
  v1.20/openshift-dedicated/PRODUCT.yaml
  v1.20/openshift-dedicated/README.md
  v1.20/openshift-dedicated/e2e.log
  v1.20/openshift-dedicated/junit_01.xml
Labels: release-documents-checked, release-v1.20, required-tests-missing

#1355 Conformance results for v1.19/oke
  v1.19/oke/PRODUCT.yaml
  v1.19/oke/README.md
  v1.19/oke/e2e.log
  v1.19/oke/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1359 Conformance results for v1.20/kubeone
  v1.20/kubeone/PRODUCT.yaml
  v1.20/kubeone/README.md
  v1.20/kubeone/e2e.log
  v1.20/kubeone/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1362 Conformance Results for v1.20/AlibabaCloud
  v1.20/alicloud/PRODUCT.yaml
  v1.20/alicloud/README.md
  v1.20/alicloud/cluster.png
  v1.20/alicloud/e2e.log
  v1.20/alicloud/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1364 Conformance results for v1.20/talos
  v1.20/talos/PRODUCT.yaml
  v1.20/talos/README.md
  v1.20/talos/e2e.log
  v1.20/talos/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1365 Conformance results for v1.19/FJcloud-V Kubernetes Service Hatoba
  v1.19/fjcloud-v-kubernetes-service-hatoba/PRODUCT.yaml
  v1.19/fjcloud-v-kubernetes-service-hatoba/README.md
  v1.19/fjcloud-v-kubernetes-service-hatoba/e2e.log
  v1.19/fjcloud-v-kubernetes-service-hatoba/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1366 Conformance results for v1.20/vmware-tanzu-kubernetes-grid
  v1.20/vmware-tanzu-kubernetes-grid/PRODUCT.yaml
  v1.20/vmware-tanzu-kubernetes-grid/README.md
  v1.20/vmware-tanzu-kubernetes-grid/e2e.log
  v1.20/vmware-tanzu-kubernetes-grid/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1368 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1369 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1370 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1371 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1372 Update conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1378 Conformance test results for v1.20/rke-government
  v1.20/rke-government/PRODUCT.yaml
  v1.20/rke-government/README.md
  v1.20/rke-government/e2e.log
  v1.20/rke-government/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1377 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1351 Conformance results for v1.19/platform9
  v1.19/platform9/PRODUCT.yaml
  v1.19/platform9/README.md
  v1.19/platform9/e2e.log
  v1.19/platform9/junit_01.xml
  v1.19/platform9/sonobuoy.tar.gz
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1326 Conformance results for v1.20/kubeasz
  v1.20/kubeasz/PRODUCT.yaml
  v1.20/kubeasz/README.md
  v1.20/kubeasz/e2e.log
  v1.20/kubeasz/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1358 Conformance results for v1.18/kubekey
  v1.18/kubekey/PRODUCT.yaml
  v1.18/kubekey/README.md
  v1.18/kubekey/e2e.log
  v1.18/kubekey/junit_01.xml
  v1.18/kubekey/sonobuoy.tar.gz
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1376 Rebrand NIFCLOUD Hatoba to NIFCLOUD Kubernetes Service Hatoba v1.18
  v1.18/nifcloud-hatoba/PRODUCT.yaml
  v1.18/nifcloud-kubernetes-service-hatoba/PRODUCT.yaml
  v1.18/nifcloud-kubernetes-service-hatoba/README.md
  v1.18/nifcloud-kubernetes-service-hatoba/e2e.log
  v1.18/nifcloud-kubernetes-service-hatoba/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1382 Conformance results for v1.18/Bonc
  v1.18/bonc/PRODUCT.yaml
  v1.18/bonc/README.md
  v1.18/bonc/e2e.log
  v1.18/bonc/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1384 Conformance results for v1.19/elastisys-compliant-kubernetes
  v1.19/elastisys-compliant-kubernetes/PRODUCT.yaml
  v1.19/elastisys-compliant-kubernetes/README.md
  v1.19/elastisys-compliant-kubernetes/e2e.log
  v1.19/elastisys-compliant-kubernetes/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1385 Conformance results for v1.21/scaleway
  v1.21/scaleway/PRODUCT.yaml
  v1.21/scaleway/README.md
  v1.21/scaleway/e2e.log
  v1.21/scaleway/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1386 Conformance results for v1.21/typhoon
  v1.21/PRODUCT.yaml
  v1.21/README.md
  v1.21/e2e.log
  v1.21/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1388 Conformance results for v1.20/mirantis
  v1.20/mirantis-docker-enterprise/PRODUCT.yaml
  v1.20/mirantis-docker-enterprise/README.md
  v1.20/mirantis-docker-enterprise/e2e.log
  v1.20/mirantis-docker-enterprise/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1405 Update conformance results for v1.18/ibm-openshift
  v1.18/ibm-openshift/PRODUCT.yaml
  v1.18/ibm-openshift/e2e.log
  v1.18/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18

#1403 Updated conformance results for IKS v1.18
  v1.18/iks/PRODUCT.yaml
  v1.18/iks/e2e.log
  v1.18/iks/junit_01.xml
Labels: no-failed-tests-v1.18, release-documents-checked, release-v1.18, tests-verified-v1.18
