Repository cncf/k8s-conformance, pull requests merged in 2021-09, with the labels that each got.

#1589 Conformance results for v1.20/giantswarm-kvm
  v1.20/giantswarm-kvm/PRODUCT.yaml
  v1.20/giantswarm-kvm/README.md
  v1.20/giantswarm-kvm/e2e.log
  v1.20/giantswarm-kvm/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1590 Conformance results for v1.22/flexkube
  v1.22/flexkube/PRODUCT.yaml
  v1.22/flexkube/README.md
  v1.22/flexkube/e2e.log
  v1.22/flexkube/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1591 Conformance results for v1.21/kubeone
  v1.21/kubeone/PRODUCT.yaml
  v1.21/kubeone/README.md
  v1.21/kubeone/e2e.log
  v1.21/kubeone/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1592 Conformance results for v1.22/kubeone
  v1.22/kubeone/PRODUCT.yaml
  v1.22/kubeone/README.md
  v1.22/kubeone/e2e.log
  v1.22/kubeone/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1593 TKGI / PKS 1.12 conformance with Kubernetes v1.21
  v1.21/pks/PRODUCT.yaml
  v1.21/pks/README.md
  v1.21/pks/e2e.log
  v1.21/pks/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1594 Conformance test results for v1.22/MicroK8s
  v1.22/microk8s/PRODUCT.yaml
  v1.22/microk8s/README.md
  v1.22/microk8s/e2e.log
  v1.22/microk8s/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1595 Conformance results for v1.21/vmware-tanzu-kubernetes-grid
  v1.21/vmware-tanzu-kubernetes-grid/PRODUCT.yaml
  v1.21/vmware-tanzu-kubernetes-grid/README.md
  v1.21/vmware-tanzu-kubernetes-grid/e2e.log
  v1.21/vmware-tanzu-kubernetes-grid/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1571 Conformance results for v1.22/desktop-kubernetes
  v1.22/desktop-kubernetes/PRODUCT.yaml
  v1.22/desktop-kubernetes/README.md
  v1.22/desktop-kubernetes/e2e.log
  v1.22/desktop-kubernetes/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1596 Conformance results for v1.21/giantswarm-kvm
  v1.21/giantswarm-kvm/PRODUCT.yaml
  v1.21/giantswarm-kvm/README.md
  v1.21/giantswarm-kvm/e2e.log
  v1.21/giantswarm-kvm/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1599 Conformance results for v1.19/kubermatic
  v1.19/kubermatic/PRODUCT.yaml
  v1.19/kubermatic/README.md
  v1.19/kubermatic/e2e.log
  v1.19/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1598 Conformance results for v1.20/kubermatic
  v1.20/kubermatic/PRODUCT.yaml
  v1.20/kubermatic/e2e.log
  v1.20/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1597 Conformance results for v1.21/kubermatic
  v1.21/kubermatic/PRODUCT.yaml
  v1.21/kubermatic/README.md
  v1.21/kubermatic/e2e.log
  v1.21/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1600 Conformance results for v1.22/talos
  v1.22/talos/PRODUCT.yaml
  v1.22/talos/README.md
  v1.22/talos/e2e.log
  v1.22/talos/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1601 conformance results for elastisys compliant kuberntetes v1.20
  v1.20/elastisys-compliant-kubernetes/PRODUCT.yaml
  v1.20/elastisys-compliant-kubernetes/README.md
  v1.20/elastisys-compliant-kubernetes/e2e.log
  v1.20/elastisys-compliant-kubernetes/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1602 Add conformance results for v1.22/fury
  v1.22/fury-distribution/PRODUCT.yaml
  v1.22/fury-distribution/README.md
  v1.22/fury-distribution/e2e.log
  v1.22/fury-distribution/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1606 Conformance results for v1.19/kubermatic
  v1.19/kubermatic/PRODUCT.yaml
  v1.19/kubermatic/README.md
  v1.19/kubermatic/e2e.log
  v1.19/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1607 Conformance results for v1.20/kubermatic
  v1.20/kubermatic/PRODUCT.yaml
  v1.20/kubermatic/README.md
  v1.20/kubermatic/e2e.log
  v1.20/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1608 Conformance results for v1.21/kubermatic
  v1.21/kubermatic/PRODUCT.yaml
  v1.21/kubermatic/README.md
  v1.21/kubermatic/e2e.log
  v1.21/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1609 Conformance results for v1.22/kubermatic
  v1.22/kubermatic/PRODUCT.yaml
  v1.22/kubermatic/README.md
  v1.22/kubermatic/e2e.log
  v1.22/kubermatic/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1612 Add conformance results for v1.21/k8s-tew
  v1.21/k8s-tew/PRODUCT.yaml
  v1.21/k8s-tew/README.md
  v1.21/k8s-tew/e2e.log
  v1.21/k8s-tew/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1611 Conformance results for v1.21/kbsys_Bizmicro_Portal_New
  v1.21/kbsys_Bizmicro_Portal_New/PRODUCT.yaml
  v1.21/kbsys_Bizmicro_Portal_New/README.md
  v1.21/kbsys_Bizmicro_Portal_New/e2e.log
  v1.21/kbsys_Bizmicro_Portal_New/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1610 Conformance results for v1.20/KubeCube
  v1.20/KubeCube/PRODUCT.yaml
  v1.20/KubeCube/README.md
  v1.20/KubeCube/e2e.log
  v1.20/KubeCube/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1617 EKS Anywhere v1.20 conformance
  v1.20/eks-a/PRODUCT.yaml
  v1.20/eks-a/README.md
  v1.20/eks-a/e2e.log
  v1.20/eks-a/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1619 Conformance results for v1.20/nirmata
  v1.20/nirmata/PRODUCT.yaml
  v1.20/nirmata/README.md
  v1.20/nirmata/e2e.log
  v1.20/nirmata/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1627 Conformance results for v1.21/nirmata
  v1.21/nirmata/PRODUCT.yaml
  v1.21/nirmata/README.md
  v1.21/nirmata/e2e.log
  v1.21/nirmata/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1625 Conformance results for v1.21/HUAWEICLOUD Cloud Container Engine
  v1.21/huawei-cce/PRODUCT.yaml
  v1.21/huawei-cce/README.md
  v1.21/huawei-cce/e2e.log
  v1.21/huawei-cce/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1626 Conformance results for v1.20/cloudboostr
  v1.20/cloudboostr/PRODUCT.yaml
  v1.20/cloudboostr/README.md
  v1.20/cloudboostr/e2e.log
  v1.20/cloudboostr/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1628 Conformance results for v1.20/QingCloud KubeSphere Engine (QKE)
  v1.20/QKE/PRODUCT.yaml
  v1.20/QKE/QingCloudLogo.ai
  v1.20/QKE/README.md
  v1.20/QKE/e2e.log
  v1.20/QKE/guide1.png
  v1.20/QKE/guide2.png
  v1.20/QKE/guide3.png
  v1.20/QKE/guide4.png
  v1.20/QKE/guide5.png
  v1.20/QKE/guide6.png
  v1.20/QKE/guide7.png
  v1.20/QKE/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1629 Conformance results for v1.22/easystack
  v1.22/easystack/PRODUCT.yaml
  v1.22/easystack/README.md
  v1.22/easystack/e2e.log
  v1.22/easystack/images/k8s2.png
  v1.22/easystack/images/k8s3.png
  v1.22/easystack/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1630 Conformance results for v1.22/kubic
  v1.22/kubic/PRODUCT.yaml
  v1.22/kubic/README.md
  v1.22/kubic/e2e.log
  v1.22/kubic/junit_01.xml
  v1.22/kubic/sonobuoy.tar.gz
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1632 Conformance results for v1.22/symplegma
  v1.22/symplegma/PRODUCT.yaml
  v1.22/symplegma/README.md
  v1.22/symplegma/e2e.log
  v1.22/symplegma/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1633 Conformance results for v1.22/kubeasz
  v1.22/kubeasz/PRODUCT.yaml
  v1.22/kubeasz/README.md
  v1.22/kubeasz/e2e.log
  v1.22/kubeasz/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1634 Conformance results for v1.22/dahua-MagicCube
  v1.22/dahua-MagicCube/1.png
  v1.22/dahua-MagicCube/2.png
  v1.22/dahua-MagicCube/3.png
  v1.22/dahua-MagicCube/4.png
  v1.22/dahua-MagicCube/PRODUCT.yaml
  v1.22/dahua-MagicCube/README.md
  v1.22/dahua-MagicCube/e2e.log
  v1.22/dahua-MagicCube/junit_01.xml
  v1.22/dahua-MagicCube/overallarch.bmp
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1635 Conformance results for v1.21/ELASTX
  v1.21/elastx/PRODUCT.yaml
  v1.21/elastx/README.md
  v1.21/elastx/e2e.log
  v1.21/elastx/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1618 Conformance results for v1.22/k3s
  v1.22/k3s/PRODUCT.yaml
  v1.22/k3s/README.md
  v1.22/k3s/e2e.log
  v1.22/k3s/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1636 ACP v1.21 conformance
  v1.21/acp/PRODUCT.yaml
  v1.21/acp/README.md
  v1.21/acp/e2e.log
  v1.21/acp/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1637 Conformance results for v1.21/giantswarm-aws
  v1.21/giantswarm-aws/PRODUCT.yaml
  v1.21/giantswarm-aws/README.md
  v1.21/giantswarm-aws/e2e.log
  v1.21/giantswarm-aws/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1638 Conformance results for v1.22/h3c-cloudos
  v1.22/h3c-cloudos/PRODUCT.yaml
  v1.22/h3c-cloudos/README.md
  v1.22/h3c-cloudos/e2e.log
  v1.22/h3c-cloudos/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1639 Conformance test results for v1.21/aks-engine
  v1.21/aks-engine/PRODUCT.yaml
  v1.21/aks-engine/README.md
  v1.21/aks-engine/e2e.log
  v1.21/aks-engine/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1631 Conformance results for v1.20/stackit-kubernetes-engine
  v1.20/stackit-kubernetes-engine/PRODUCT.yaml
  v1.20/stackit-kubernetes-engine/README.md
  v1.20/stackit-kubernetes-engine/e2e.log
  v1.20/stackit-kubernetes-engine/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1647 New conformance results for v1.21/ibm-openshift
  v1.21/ibm-openshift/PRODUCT.yaml
  v1.21/ibm-openshift/README.md
  v1.21/ibm-openshift/e2e.log
  v1.21/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1645 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1644 Update conformance results for v1.20/ibm-openshift
  v1.20/ibm-openshift/PRODUCT.yaml
  v1.20/ibm-openshift/README.md
  v1.20/ibm-openshift/e2e.log
  v1.20/ibm-openshift/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1643 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: release-documents-checked, release-v1.19, tests-verified-v1.19, no-failed-tests-v1.19

#1642 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1641 Updated conformance results for IKS v1.21
  v1.21/iks/PRODUCT.yaml
  v1.21/iks/e2e.log
  v1.21/iks/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1649 Conformance results for v1.21/airship
  v1.21/airship/PRODUCT.yaml
  v1.21/airship/README.md
  v1.21/airship/e2e.log
  v1.21/airship/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1650 Conformance results for v1.20/veCompass
  v1.20/veCompass/PRODUCT.yaml
  v1.20/veCompass/README.md
  v1.20/veCompass/e2e.log
  v1.20/veCompass/junit_01.xml
Labels: release-documents-checked, release-v1.20, tests-verified-v1.20, no-failed-tests-v1.20

#1651 Conformance results for v1.22/openpalette 🐳
  v1.22/openpalette/PRODUCT.yaml
  v1.22/openpalette/README.md
  v1.22/openpalette/e2e.log
  v1.22/openpalette/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22
