Repository cncf/k8s-conformance, pull requests merged in 2021-07, with the labels that each got.

#1507 Conformance results for v1.20/ELASTX
  v1.20/elastx/PRODUCT.yaml
  v1.20/elastx/README.md
  v1.20/elastx/e2e.log
  v1.20/elastx/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1513 Conformance Results for v1.20/rafay
  v1.20/rafay/PRODUCT.yaml
  v1.20/rafay/README.md
  v1.20/rafay/Rafay_Logo.png
  v1.20/rafay/Rafay_Logo.svg
  v1.20/rafay/e2e.log
  v1.20/rafay/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1514 Conformance results for v1.20/puppetlabs-kubernetes
  v1.20/puppetlabs-kubernetes/PRODUCT.yaml
  v1.20/puppetlabs-kubernetes/README.md
  v1.20/puppetlabs-kubernetes/e2e.log
  v1.20/puppetlabs-kubernetes/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1517 Conformance results for v1.20/exoscale
  v1.20/exoscale/PRODUCT.yaml
  v1.20/exoscale/README.md
  v1.20/exoscale/e2e.log
  v1.20/exoscale/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1518 Conformance results for v1.21/exoscale
  v1.21/exoscale/PRODUCT.yaml
  v1.21/exoscale/README.md
  v1.21/exoscale/e2e.log
  v1.21/exoscale/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1519 Conformance results for v1.21/gec-imke
  v1.21/gec-imke/PRODUCT.yaml
  v1.21/gec-imke/README.md
  v1.21/gec-imke/e2e.log
  v1.21/gec-imke/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1523 Conformance results for v1.21/rafay
  v1.21/rafay/PRODUCT.yaml
  v1.21/rafay/README.md
  v1.21/rafay/Rafay_Logo.png
  v1.21/rafay/Rafay_Logo.svg
  v1.21/rafay/e2e.log
  v1.21/rafay/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1536 Conformance Results for v1.19/kingsoft-container-engine
  v1.19/kingsoft-container-engine/PRODUCT.yaml
  v1.19/kingsoft-container-engine/README.md
  v1.19/kingsoft-container-engine/e2e.log
  v1.19/kingsoft-container-engine/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1527 Updated conformance results for IKS v1.21
  v1.21/iks/PRODUCT.yaml
  v1.21/iks/e2e.log
  v1.21/iks/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1528 Updated conformance results for IKS v1.20
  v1.20/iks/PRODUCT.yaml
  v1.20/iks/e2e.log
  v1.20/iks/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1529 Updated conformance results for IKS v1.19
  v1.19/iks/PRODUCT.yaml
  v1.19/iks/e2e.log
  v1.19/iks/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1530 Update conformance results for v1.20/ibm-openshift
  v1.20/ibm-openshift/PRODUCT.yaml
  v1.20/ibm-openshift/e2e.log
  v1.20/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1531 Update conformance results for v1.19/ibm-openshift
  v1.19/ibm-openshift/PRODUCT.yaml
  v1.19/ibm-openshift/e2e.log
  v1.19/ibm-openshift/junit_01.xml
Labels: no-failed-tests-v1.19, release-documents-checked, release-v1.19, tests-verified-v1.19

#1532 Conformance results for v1.21/digitalocean
  v1.21/digitalocean/PRODUCT.yaml
  v1.21/digitalocean/README.md
  v1.21/digitalocean/e2e.log
  v1.21/digitalocean/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1534 Conformance results for v1.20/baiducloud
  v1.20/baiducloud/PRODUCT.yaml
  v1.20/baiducloud/README.md
  v1.20/baiducloud/e2e.log
  v1.20/baiducloud/junit_01.xml
Labels: no-failed-tests-v1.20, release-documents-checked, release-v1.20, tests-verified-v1.20

#1520 Gec url changes
  v1.14/gec-imke/PRODUCT.yaml
  v1.15/gec-imke/PRODUCT.yaml
  v1.16/gec-imke/PRODUCT.yaml
  v1.16/gec-imke/README.md
  v1.17/gec-imke/PRODUCT.yaml
  v1.17/gec-imke/README.md
  v1.18/gec-imke/PRODUCT.yaml
  v1.18/gec-imke/README.md
  v1.19/gec-imke/PRODUCT.yaml
  v1.19/gec-imke/README.md
  v1.20/gec-imke/PRODUCT.yaml
  v1.20/gec-imke/README.md
  v1.21/gec-imke/PRODUCT.yaml
  v1.21/gec-imke/README.md
Labels: not-verifiable

#1535 Conformance test results for v1.21/rke-government
  v1.21/rke-government/PRODUCT.yaml
  v1.21/rke-government/README.md
  v1.21/rke-government/e2e.log
  v1.21/rke-government/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21

#1537 Conformance results for v1.21/gke
  v1.21/gke/PRODUCT.yaml
  v1.21/gke/README.md
  v1.21/gke/e2e.log
  v1.21/gke/junit_01.xml
Labels: no-failed-tests-v1.21, release-documents-checked, release-v1.21, tests-verified-v1.21
