Repository cncf/k8s-conformance, pull requests merged in 2022-01, with the labels that each got.

#1747 Conformance results for v1.22/AlibabaCloud
  v1.22/alicloud/PRODUCT.yaml
  v1.22/alicloud/README.md
  v1.22/alicloud/e2e.log
  v1.22/alicloud/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1748 Conformance results for v1.21/kubespray
  v1.21/kubespray/PRODUCT.yaml
  v1.21/kubespray/README.md
  v1.21/kubespray/e2e.log
  v1.21/kubespray/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1751 Conformance results for v1.23/minikube
  v1.23/minikube/PRODUCT.yaml
  v1.23/minikube/README.md
  v1.23/minikube/e2e.log
  v1.23/minikube/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1752 Conformance results for v1.23/talos (#1600)
  v1.23/talos/PRODUCT.yaml
  v1.23/talos/README.md
  v1.23/talos/e2e.log
  v1.23/talos/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1754 conformance tests for platform9 v1.21
  v1.21/platform9/PRODUCT.yaml
  v1.21/platform9/README.md
  v1.21/platform9/e2e.log
  v1.21/platform9/junit_01.xml
  v1.21/platform9/sonobuoy.tar.gz
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1755 Conformance results for v1.23/k0s v1.23.1+k0s.0
  v1.23/k0s/PRODUCT.yaml
  v1.23/k0s/README.md
  v1.23/k0s/e2e.log
  v1.23/k0s/junit_01.xml
  v1.23/k0s/sonobuoy_results.tar.gz
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1758 AWS EKS-A conformance v1.21
  v1.21/eks-a/PRODUCT.yaml
  v1.21/eks-a/README.md
  v1.21/eks-a/e2e.log
  v1.21/eks-a/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1759 Conformance results for v1.22/baiducloud
  v1.22/baiducloud/PRODUCT.yaml
  v1.22/baiducloud/README.md
  v1.22/baiducloud/e2e.log
  v1.22/baiducloud/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1760 Conformance results for v1.22/kubespray
  v1.22/kubespray/PRODUCT.yaml
  v1.22/kubespray/README.md
  v1.22/kubespray/e2e.log
  v1.22/kubespray/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1761 Conformance results for v1.21/nexastack
  v1.21/nexastack/PRODUCT.yaml
  v1.21/nexastack/Please_DocuSign_Certified_Kubernetes_Form.pd.pdf
  v1.21/nexastack/README.md
  v1.21/nexastack/e2e.log
  v1.21/nexastack/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1750 Conformance Results for v1.22/rafay
  v1.22/rafay/PRODUCT.yaml
  v1.22/rafay/README.md
  v1.22/rafay/Rafay_Logo.svg
  v1.22/rafay/e2e.log
  v1.22/rafay/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1757 Conformance results for v1.21/ridge
  v1.21/ridge/PRODUCT.yaml
  v1.21/ridge/README.md
  v1.21/ridge/e2e.log
  v1.21/ridge/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1762 Conformance results for v1.23/kubeasz
  v1.23/kubeasz/PRODUCT.yaml
  v1.23/kubeasz/README.md
  v1.23/kubeasz/e2e.log
  v1.23/kubeasz/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1753 Conformance results for v1.21/openstack-magnum
  v1.21/openstack-magnum/PRODUCT.yaml
  v1.21/openstack-magnum/README.md
  v1.21/openstack-magnum/e2e.log
  v1.21/openstack-magnum/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1756 Conformance results for v1.22/k0s v1.22.5+k0s.0
  v1.22/k0s/PRODUCT.yaml
  v1.22/k0s/README.md
  v1.22/k0s/e2e.log
  v1.22/k0s/junit_01.xml
  v1.22/k0s/sonobuoy_results.tar.gz
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1763 Nutanix Karbon k8s v1.21 conformance
  v1.21/ntnx-karbon/PRODUCT.yaml
  v1.21/ntnx-karbon/README.md
  v1.21/ntnx-karbon/e2e.log
  v1.21/ntnx-karbon/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1764 Conformance results for v1.23/ecloud
  v1.23/ecloud/PRODUCT.yaml
  v1.23/ecloud/README.md
  v1.23/ecloud/e2e.log
  v1.23/ecloud/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1766 ucloud k8s conformance v1.22.5
  v1.22/UCloud/PRODUCT.yaml
  v1.22/UCloud/README.md
  v1.22/UCloud/e2e.log
  v1.22/UCloud/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1767 Conformance test results for v1.23/k3s
  v1.23/k3s/PRODUCT.yaml
  v1.23/k3s/README.md
  v1.23/k3s/e2e.log
  v1.23/k3s/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1768 Conformance results for v1.22/TencentCloud
  v1.22/tencentcloud/CreateTkeCluster.png
  v1.22/tencentcloud/PRODUCT.yaml
  v1.22/tencentcloud/README.md
  v1.22/tencentcloud/e2e.log
  v1.22/tencentcloud/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1769 comformance results for elastisys compliant kubernetes v1.21
  v1.21/elastisys-compliant-kubernetes/PRODUCT.yaml
  v1.21/elastisys-compliant-kubernetes/README.md
  v1.21/elastisys-compliant-kubernetes/e2e.log
  v1.21/elastisys-compliant-kubernetes/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1770 Conformance test results for v1.21/Weave GitOps Enterprise
  v1.21/weave gitops enterprise/PRODUCT.yaml
  v1.21/weave gitops enterprise/README.MD
  v1.21/weave gitops enterprise/e2e.log
  v1.21/weave gitops enterprise/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1765 Conformance results for v1.22/smart-edge-open
  v1.22/smart-edge-open/PRODUCT.yaml
  v1.22/smart-edge-open/README.md
  v1.22/smart-edge-open/e2e.log
  v1.22/smart-edge-open/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1771 Conformance results for v1.23/inspur-iop-amd64
  v1.23/inspur-iop-amd64/PRODUCT.yaml
  v1.23/inspur-iop-amd64/README.md
  v1.23/inspur-iop-amd64/e2e.log
  v1.23/inspur-iop-amd64/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1773 Conformance results for v1.23/symplegma
  v1.23/symplegma/PRODUCT.yaml
  v1.23/symplegma/README.md
  v1.23/symplegma/e2e.log
  v1.23/symplegma/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1775 Conformance results for v1.22/deckhouse
  v1.22/deckhouse/PRODUCT.yaml
  v1.22/deckhouse/README.md
  v1.22/deckhouse/e2e.log
  v1.22/deckhouse/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1774 Conformance results for v1.22.1/chinaunicomcloud
  v1.22/chinaunicomcloud/PRODUCT.yaml
  v1.22/chinaunicomcloud/README.md
  v1.22/chinaunicomcloud/cluster.png
  v1.22/chinaunicomcloud/e2e.log
  v1.22/chinaunicomcloud/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1776 Conformance results for v1.21/puppetlabs-kubernetes
  v1.21/puppetlabs-kubernetes/PRODUCT.yaml
  v1.21/puppetlabs-kubernetes/README.md
  v1.21/puppetlabs-kubernetes/e2e.log
  v1.21/puppetlabs-kubernetes/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1781 Add OSD v4.9 (1.22) conformance
  v1.22/openshift-dedicated/PRODUCT.yaml
  v1.22/openshift-dedicated/README.md
  v1.22/openshift-dedicated/e2e.log
  v1.22/openshift-dedicated/junit_01.xml
Labels: not-verifiable

#1778 Conformance results for v1.21/QingCloud KubeSphere Engine (QKE)
  v1.21/QKE/PRODUCT.yaml
  v1.21/QKE/QingCloudLogo.ai
  v1.21/QKE/README.md
  v1.21/QKE/e2e.log
  v1.21/QKE/guide1.png
  v1.21/QKE/guide2.png
  v1.21/QKE/guide3.png
  v1.21/QKE/guide4.png
  v1.21/QKE/guide5.png
  v1.21/QKE/guide6.png
  v1.21/QKE/guide7.png
  v1.21/QKE/junit_01.xml
Labels: release-documents-checked, release-v1.21, tests-verified-v1.21, no-failed-tests-v1.21

#1780 Conformance results for v1.23/inspur-iop-arm64
  v1.23/inspur-iop-arm64/PRODUCT.yaml
  v1.23/inspur-iop-arm64/README.md
  v1.23/inspur-iop-arm64/e2e.log
  v1.23/inspur-iop-arm64/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1788 Add conformance results for v1.23/fury-distribution
  v1.23/fury-distribution/PRODUCT.yaml
  v1.23/fury-distribution/README.md
  v1.23/fury-distribution/e2e.log
  v1.23/fury-distribution/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1790 Conformance results for v1.23/nirmata
  v1.23/nirmata/PRODUCT.yaml
  v1.23/nirmata/README.md
  v1.23/nirmata/e2e.log
  v1.23/nirmata/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1791 Conformance results for v1.23/kublr
  v1.23/kublr/PRODUCT.yaml
  v1.23/kublr/README.md
  v1.23/kublr/e2e.log
  v1.23/kublr/junit_01.xml
Labels: release-documents-checked, release-v1.23, tests-verified-v1.23, no-failed-tests-v1.23

#1792 Conformance results for v1.22/vke
  v1.22/vke/PRODUCT.yaml
  v1.22/vke/README.md
  v1.22/vke/e2e.log
  v1.22/vke/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22

#1793 Conformance results for v1.22/vcluster
  v1.22/vcluster/PRODUCT.yaml
  v1.22/vcluster/README.md
  v1.22/vcluster/e2e.log
  v1.22/vcluster/junit_01.xml
Labels: release-documents-checked, release-v1.22, tests-verified-v1.22, no-failed-tests-v1.22
